<form method="post" class="mdl-grid">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
    <input class="mdl-textfield__input" type="text" value="<?= $user->username ?>" id="username" readonly>
    <label class="mdl-textfield__label" for="username">Nama Pengguna</label>
  </div>
  <div class="mdl-cell mdl-cell--12-col buttons">
    <a href="./change-password" class="mdl-button mdl-button--raised mdl-button--primary mdl-js-button mdl-js-ripple-effect">
      <i class="material-icons left">vpn_key</i>Ganti Kata Sandi</a>
  </div>
</form>