<div class="mdl-grid apps">
  <?php if (current_user_can('open-shiftnet-app')): ?>
  <a href="<?= BASE_URL ?>/shiftnet/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">device_hub</i><br>ShiftNet</a>
  <?php endif ?>
  <?php if (current_user_can('open-pos-app')): ?>
  <a href="<?= BASE_URL ?>/pos/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">store</i><br>POS</a>
  <?php endif ?>
  <?php if (current_user_can('open-finance-app')): ?>
  <a href="<?= BASE_URL ?>/finance/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">local_atm</i><br>Keuangan</a>
  <?php endif ?>
  <?php if (current_user_can('open-credit-app')): ?>
  <a href="<?= BASE_URL ?>/credit/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">payment</i><br>Kredit</a>
  <?php endif ?>
</div>
<?php if ($_SESSION['CURRENT_USER']->groupId == 1): ?>
<div class="mdl-grid apps">
  <a href="<?= BASE_URL ?>/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">show_chart</i><br>Laporan</a>
  <a href="<?= BASE_URL ?>/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">settings</i><br>Sistem</a>
</div>
<?php endif ?>