<form method="post" class="mdl-grid">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?=
    !empty($errors['password0']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="password0" name="password0">
    <label class="mdl-textfield__label" for="password0">Kata Sandi Lama</label>
    <?php if (!empty($errors['password0'])): ?>
      <span class="form-error"><?= $errors['password0'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?=
    !empty($errors['password1']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="password1" name="password1">
    <label class="mdl-textfield__label" for="password1">Kata Sandi Baru</label>
    <?php if (!empty($errors['password1'])): ?>
      <span class="form-error"><?= $errors['password1'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?=
    !empty($errors['password2']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="password2" name="password2">
    <label class="mdl-textfield__label" for="password2">Konfirmasi Kata Sandi Baru</label>
    <?php if (!empty($errors['password2'])): ?>
      <span class="form-error"><?= $errors['password2'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-cell mdl-cell--12-col buttons">
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit">
      <i class="material-icons left">check</i>Simpan</button>
    <a href="./account" class="mdl-button mdl-button--raised  mdl-js-button mdl-js-ripple-effect">
      <i class="material-icons left">close</i>Batal</a>
  </div>
</form>