<script>APP_BASE_URL='<?= BASE_URL ?>';</script>
<script src="<?= JS_BASE_URL ?>material.min.js"></script>
<?php if (isset($_SESSION['FLASH_MESSAGE'])): ?>
  <div id="snackbar-container" class="mdl-js-snackbar mdl-snackbar">
    <div class="mdl-snackbar__text"></div>
    <button class="mdl-snackbar__action" type="button"></button>
  </div>
  <script>
    (function showSnackbar() {
      var snackbarContainer = document.querySelector('#snackbar-container');
      
      if (!snackbarContainer.MaterialSnackbar) {
        setTimeout(showSnackbar, 1000);
        return;
      }
      
      snackbarContainer.MaterialSnackbar.showSnackbar({
        message:'<?= $_SESSION['FLASH_MESSAGE'] ?>'
      });
    })();
  </script>
  <?php unset($_SESSION['FLASH_MESSAGE']) ?>
<?php endif ?>