<div id="submit-progress" style="position:fixed;top:0;left:0;right:0;bottom:0;z-index:100;display:none;">
  <div class="mdl-progress mdl-js-progress mdl-progress__indeterminate mdl-spinner--single-color" style="width:100%;height:5px;"></div>
</div>
<script src="<?= JS_BASE_URL ?>material.min.js"></script>
<script src="<?= JS_BASE_URL ?>material.selectfield.min.js"></script>
<?php if (isset($_SESSION['FLASH_MESSAGE'])): ?>
  <div id="snackbar-container" class="mdl-js-snackbar mdl-snackbar">
    <div class="mdl-snackbar__text"></div>
    <button class="mdl-snackbar__action" type="button"></button>
  </div>
  <script>
    (function showSnackbar() {
      var snackbarContainer = document.querySelector('#snackbar-container');
      
      if (!snackbarContainer.MaterialSnackbar) {
        setTimeout(showSnackbar, 1000);
        return;
      }
      
      snackbarContainer.MaterialSnackbar.showSnackbar({
        message:'<?= $_SESSION['FLASH_MESSAGE'] ?>'
      });
    })();
  </script>
  <?php unset($_SESSION['FLASH_MESSAGE']) ?>
<?php endif ?>
<script>
  Number.prototype.toLocale = function(c, d, t){
    var n = this, 
        c = isNaN(c = Math.abs(c)) ? 0 : c, 
        d = d === undefined ? "," : d, 
        t = t === undefined ? "." : t, 
        s = n < 0 ? "-" : "", 
        i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))), 
        j = (j = i.length) > 3 ? j % 3 : 0;
    return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
  };
  
  String.prototype.toLocaleNumber = function() {
    return parseFloat(this.replace(/\./g, '').replace(/,/g, '.'));
  }
  function confirmOnClick(q, m) { var e = document.querySelector(q); if (e) e.addEventListener('click', function(e) { if (!confirm(m)) { e.preventDefault(); return; } }); }
  function showSubmitProgress() { document.querySelector('#submit-progress').style.display = 'block'; }
  document.querySelectorAll('form').forEach(function(form) { form.addEventListener('submit', showSubmitProgress); });
  document.querySelectorAll('.numberEditor').forEach(function(input) {
    input.addEventListener('focus', function() { this.select(); });
    input.addEventListener('blur', function() { this.value = parseInt(this.value.replace(/\./g, '').replace(/,/g, '.')).toLocale(); });
  });
  function setupStandardFilterDialog() {
    var filterDialog = document.querySelector('#filter-dialog');
    if (!filterDialog) return;
    if (!filterDialog.showModal) { dialogPolyfill.registerDialog(filterDialog); }
    document.querySelector('#filter-dialog .close').addEventListener('click', function() { filterDialog.close(); });
    document.querySelector('#filter-button').addEventListener('click', function() { filterDialog.showModal(); });
  }
  document.querySelectorAll('a').forEach(function (a) { a.addEventListener('click', showSubmitProgress); });
</script>