<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="white">
<meta name="apple-mobile-web-app-title" content="Shift IMS">
<title><?= (empty($title) ? '' : $title . ' - ') .  'Shift IMS' ?></title>
<link rel="stylesheet" href="<?= CSS_BASE_URL ?>material-icons.css">
<link rel="stylesheet" href="<?= CSS_BASE_URL ?>material.min.css">
<link rel="stylesheet" href="<?= CSS_BASE_URL ?>material.selectfield.min.css">
<link rel="stylesheet" href="<?= CSS_BASE_URL ?>global.css">