<div class="mdl-grid apps">
  <a href="<?= BASE_URL ?>/shiftnet/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">device_hub</i><br>ShiftNet</a>
  <a href="<?= BASE_URL ?>/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">store</i><br>Penjualan</a>
  <a href="<?= BASE_URL ?>/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">build</i><br>Servis</a>
  <a href="<?= BASE_URL ?>/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">local_atm</i><br>Keuangan</a>
</div>
<div class="mdl-grid apps">
  <a href="<?= BASE_URL ?>/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">show_chart</i><br>Laporan</a>
  <a href="<?= BASE_URL ?>/" class="mdl-cell mdl-cell--1-col"><i class="material-icons">settings</i><br>Sistem</a>
</div>
