<!DOCTYPE html>
<html>
  <head>
    <?= render('head') ?>
    <style>
      .mdl-card { width: 300px; }
      .mdl-layout { align-items: center; justify-content: center; }
      .mdl-layout__content { padding: 24px; flex: none; }
      .mdl-card__title-text { display: block; text-align: center; width: 100%; }
      .mdl-card__actions { padding: 16px; }
      .mdl-button { width: 100%; height: 50px; }
    </style>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-color--grey-100">
      <main class="mdl-layout__content">
        <div class="mdl-card mdl-shadow--6dp">
          <form method="POST">
            <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
              <h2 class="mdl-card__title-text">Shift IMS</h2>
            </div>        
            <div class="mdl-card__supporting-text">
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label <?= !empty($errors['username']) ? 'is-invalid' : '' ?>">
                <input class="mdl-textfield__input" type="text" id="u" name="username" value="<?= e($username) ?>">
                <label class="mdl-textfield__label" for="u">Nama Pengguna</label>
                <?php if (!empty($errors['username'])): ?>
                  <span class="form-error"><?= $errors['username'] ?></span>
                <?php endif ?>
              </div>
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label <?= !empty($errors['password']) ? 'is-invalid' : '' ?>">
                <input class="mdl-textfield__input" type="password" id="p" name="password">
                <label class="mdl-textfield__label" for="p">Kata Sandi</label>
                <?php if (!empty($errors['password'])): ?>
                  <div class="form-error"><?= $errors['password'] ?></div>
                <?php endif ?>
              </div>
            </div>
            <div class="mdl-card__actions mdl-card--border">
              <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit">Masuk</button>
            </div>
          </form>
        </div>
      </main>
    </div>
    <?= render('foot') ?>
  </body>
</html>
