<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
    h5 { font-size: 15px; }
  </style>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Kredit</span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </header>
      <?= render('credit/drawer') ?>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-cell mdl-cell--12-col">
            <h5>Total Piutang Rp. <?= format_number($total) ?></h5>
          </div>
        </div>
      </main>
    </div>
    <?= render('foot') ?>
  </body>
</html>
