<form method="POST" class="mdl-grid">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col <?=
    !empty($errors['username']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="text" value="<?= e($username) ?>" maxlength="40"
           id="username" name="new_username">
    <label class="mdl-textfield__label" for="username">Nama Pengguna</label>
    <?php if (!empty($errors['username'])): ?>
      <span class="form-error"><?= $errors['username'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-cell mdl-cell--6-col">
    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="active">
      <input type="checkbox" id="active" class="mdl-checkbox__input" value="1" name="active" <?= $active ? 'checked' : '' ?>>
      <span class="mdl-checkbox__label">Aktif (dapat login)</span>
    </label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col <?=
    !empty($errors['password1']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="password1" name="password1">
    <label class="mdl-textfield__label" for="password1">Buat Kata Sandi</label>
    <?php if (!empty($errors['password1'])): ?>
      <span class="form-error"><?= $errors['password1'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col <?=
    !empty($errors['password2']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="password2" name="password2">
    <label class="mdl-textfield__label" for="password2">Konfirmasi Kata Sandi</label>
    <?php if (!empty($errors['password2'])): ?>
      <span class="form-error"><?= $errors['password2'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-cell mdl-cell--12-col buttons">
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit">
      <i class="material-icons left">check</i>Simpan</button>
    <a href="./" class="mdl-button mdl-button--raised  mdl-js-button mdl-js-ripple-effect">
      <i class="material-icons left">close</i>Batal</a>
  </div>
</form>