<div class="mdl-grid">
  <?php if (count($members) == 0 ): ?>
    <p class="mdl-cell mdl-cell--12-col">Belum ada member yang terdaftar.</p>
  <?php else: ?>
    <div class="mdl-cell mdl-cell--12-col mdlx-data-table--responsive mdl-shadow--2dp">
    <table class="mdl-data-table mdl-js-data-table">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">Nama Pengguna</th>
          <th class="mdl-data-table__cell--non-numeric">Status Akun</th>
          <th class="mdl-data-table__cell--non-numeric">Sisa Waktu</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($members as $member): ?>
        <tr>
          <td class="mdl-data-table__cell--non-numeric"><a href="<?= './view?id=' . $member->id ?>"><?= $member->username ?></a></td>
          <td class="mdl-data-table__cell--non-numeric"><?= $member->active ? 'Aktif' : 'Tidak Aktif' ?></td>
          <td class="mdl-data-table__cell--non-numeric"><?= format_duration($member->remainingDuration) ?></td>
        </tr>
        <?php endforeach ?>
      </tbody>
    </table>
    </div>
  <?php endif ?>  
</div>