<form method="POST" class="mdl-grid">
  <input type="hidden" name="id" value="<?= $member->id ?>">
  <h5 class="mdl-cell mdl-cell--12-col">Informasi Member</h5>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
    <input class="mdl-textfield__input" type="text" value="<?= $member->username ?>" id="username" readonly>
    <label class="mdl-textfield__label" for="username">Nama Pengguna</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col <?=
    !empty($errors['password1']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="password1" name="password1">
    <label class="mdl-textfield__label" for="password1">Kata Sandi Baru</label>
    <?php if (!empty($errors['password1'])): ?>
      <span class="form-error"><?= $errors['password1'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col <?=
    !empty($errors['password2']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="password2" name="password2">
    <label class="mdl-textfield__label" for="password2">Konfirmasi Kata Sandi Baru</label>
    <?php if (!empty($errors['password2'])): ?>
      <span class="form-error"><?= $errors['password2'] ?></span>
    <?php endif ?>
  </div>
  <h5 class="mdl-cell mdl-cell--12-col"><br>Informasi Operator</h5>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
    <input class="mdl-textfield__input" type="text" value="<?= $_SESSION['CURRENT_USER']->username ?>" id="operator" readonly>
    <label class="mdl-textfield__label" for="operator">Operator</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col <?=
    !empty($errors['operatorPassword']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="operatorPassword" name="operatorPassword">
    <label class="mdl-textfield__label" for="operatorPassword">Kata Sandi Operator</label>
    <?php if (!empty($errors['operatorPassword'])): ?>
      <span class="form-error"><?= $errors['operatorPassword'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-cell mdl-cell--12-col buttons">
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit">
      <i class="material-icons left">check</i>Simpan</button>
    <a href="./view?id=<?= $member->id ?>" class="mdl-button mdl-button--raised  mdl-js-button mdl-js-ripple-effect">
      <i class="material-icons left">close</i>Batal</a>
  </div>
</form>