<div class="mdl-grid">
  <input type="hidden" name="id" value="<?= $member->id ?>">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
    <input class="mdl-textfield__input" type="text" value="<?= $member->username ?>" id="username" readonly>
    <label class="mdl-textfield__label" for="username">Nama Pengguna</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
    <input class="mdl-textfield__input" type="text" value="<?= format_duration($member->remainingDuration) ?>"
           id="remainingDuration" readonly>
    <label class="mdl-textfield__label" for="remainingDuration">Sisa Waktu</label>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="active">
      <input type="checkbox" id="active" class="mdl-checkbox__input" value="1" disabled <?= $member->active ? 'checked' : '' ?>>
      <span class="mdl-checkbox__label">Aktif (dapat login)</span>
    </label>
  </div>
</div>

<div method="GET" class="mdl-grid">
  <h5 class="mdl-cell mdl-cell--12-col">Aktifitas 3 hari terakhir</h5>
  <?php if (empty($activities)): ?>
    <p class="mdl-cell mdl-cell--12-col">Tidak ada aktivitas.</p>
  <?php else: ?>
  <style>
    .mdl-data-table th .material-icons { vertical-align: middle; }
    .mdl-data-table tr>*{text-align:left;}
    .mdl-data-table tr>*:nth-child(1),
    .mdl-data-table tr>*:nth-child(2)
    {text-align:center;}
    .mdl-data-table tr>*:nth-child(1){width:100px;}
  </style>
  <div class="mdlx-data-table--responsive mdl-cell mdl-cell--12-col">
    <table class="mdl-data-table">
      <thead>
        <tr>
          <th><i class="material-icons">access_time</i></th>
          <th><i class="material-icons">desktop_windows</i></th>
          <th>Rincian</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($activities as $activity): ?>
        <tr>
          <td><?= date('d/m/Y H:i:s', strtotime($activity->dateTime)) ?></td>
          <td><?= $activity->clientId ?></td>
          <td><?= $activity->detail ?></td>
        </tr>
      <?php endforeach ?>
      </tbody>
    </table>
  </div>
  <?php endif ?>
</div>