<div class="mdl-grid">
  <input type="hidden" name="id" value="<?= $member->id ?>">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
    <input class="mdl-textfield__input" type="text" value="<?= $member->username ?>" id="username" readonly>
    <label class="mdl-textfield__label" for="username">Nama Pengguna</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
    <input class="mdl-textfield__input" type="text" value="<?= format_duration($member->remainingDuration) ?>"
           id="remainingDuration" readonly>
    <label class="mdl-textfield__label" for="remainingDuration">Sisa Waktu</label>
  </div>
  <div class="mdl-cell mdl-cell--4-col">
    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="active">
      <input type="checkbox" id="active" class="mdl-checkbox__input" value="1" disabled <?= $member->active ? 'checked' : '' ?>>
      <span class="mdl-checkbox__label">Aktif (dapat login)</span>
    </label>
  </div>
</div>