<form method="POST" class="mdl-grid">
  <input type="hidden" name="step" value="<?= $step ?>">
<?php if ($step === 1): ?>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col">
    <input class="mdl-textfield__input" type="text" name="datetime" id="datetime" value="<?= date('d/m/Y H:i:s') ?>" readonly>
    <label class="mdl-textfield__label" for="datetime">Waktu</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col">
    <input class="mdl-textfield__input" type="text" name="amount" id="amount" value="<?= format_number($amount) ?>" readonly>
    <label class="mdl-textfield__label" for="amount">Saldo Kas</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
    !empty($errors['actualAmount']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="text" name="actualAmount" id="actualAmount" value="<?=
      format_number($actualAmount) ?>">
    <label class="mdl-textfield__label" for="actualAmount">Jumlah Setoran</label>
    <?php if (!empty($errors['actualAmount'])): ?>
      <div class="form-error"><?= $errors['actualAmount'] ?></div>
    <?php endif ?>
  </div>
<?php elseif ($step === 2): ?>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
    <p>
      Tanggal: <?= $datetime ?>
      Jumlah Setoran: <?= format_money($amount) ?>
    </p>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
    !empty($errors['password']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="password" name="password">
    <label class="mdl-textfield__label" for="password">Kata Sandi</label>
    <?php if (!empty($errors['password'])): ?>
      <span class="form-error"><?= $errors['password'] ?></span>
    <?php endif ?>
  </div>
<?php endif ?>
  <div class="mdl-cell mdl-cell--12-col buttons">
    <button type="submit" class="mdl-button mdl-button--raised mdl-button--colored mdl-js-button mdl-js-ripple-effect">
      <i class="material-icons">arrow_forward</i>Lanjutkan
    </button>
  </div>
</form>