<div class="mdl-layout__drawer">
  <header class="mdl-color--blue-grey mdl-color-text--white">
    <span class="mdl-layout-title">
      <a class="mdl-color-text--white" href="<?= BASE_URL ?>/finance/">Keuangan</a>
    </span>
    <div class="my-account-name">
      <a class="mdl-color-text--white" href="<?= BASE_URL ?>/account"><?= $_SESSION['CURRENT_USER']->username ?></a>
      <span class="mdl-color-text--white" style="float:right;font-weight:bold;">
        <?php if ($_SESSION['CURRENT_USER']->groupId == 1): ?>
          <?= format_money(g('db')->query(
            'select ifnull(sum(balance), 0)'
            . ' from finance_accounts')->fetchColumn()) ?>
        <?php elseif (g('cfg')['store_account_id']): ?>
          <?= format_money(get_store_account_balance()) ?>
        <?php endif ?>
      </span>
    </div>
  </header>
  <nav class="mdl-navigation">
    <?php if (current_user_can('view-finance-reports')): ?>
      <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/finance/report/') ? ' active' : '' ?>"
        href="<?= BASE_URL ?>/finance/report/"><i class="material-icons">show_chart</i>Laporan</a>
    <?php endif ?>
    <?php if (current_user_can('view-finance-accounts')): ?>
      <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/finance/account/') ? ' active' : '' ?>"
        href="<?= BASE_URL ?>/finance/account/"><i class="material-icons">account_balance_wallet</i>Akun / Rekening</a>
    <?php endif ?>
    <?php if (current_user_can('view-finance-transaction-categories')): ?>
      <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/finance/transaction-category/') ? ' active' : '' ?>"
        href="<?= BASE_URL ?>/finance/transaction-category/"><i class="material-icons">grid_on</i>Kategori Transaksi</a>
    <?php endif ?>
    <hr>
    <a class="mdl-navigation__link" href="<?= BASE_URL ?>/"><i class="material-icons">arrow_back</i>Shift Apps</a>
  </nav>
</div>