<div class="mdl-layout__drawer">
  <header class="mdl-color--blue-grey mdl-color-text--white">
    <span class="mdl-layout-title">
      <a class="mdl-color-text--white" href="<?= BASE_URL ?>/finance/">Keuangan</a>
    </span>
    <span class="my-account-name"><a class="mdl-color-text--white" href="<?= BASE_URL ?>/account"><?= $_SESSION['CURRENT_USER']->username ?></a></span>
  </header>
  <nav class="mdl-navigation">
    <?php if (current_user_can('view-debts-accounts')): ?>
      <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/finance/debts/') ? ' active' : '' ?>"
        href="<?= BASE_URL ?>/finance/debts/">Utang Piutang</a>
      <hr>
    <?php endif ?>
    <?php if (current_user_can('view-finance-accounts') || current_user_can('view-finance-transaction-categories')): ?>
      <?php if (current_user_can('view-finance-accounts')): ?>
        <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/finance/account/') ? ' active' : '' ?>"
          href="<?= BASE_URL ?>/finance/account/">Akun / Rekening</a>
      <?php endif ?>
      <?php if (current_user_can('view-finance-transaction-categories')): ?>
        <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/finance/transaction-category/') ? ' active' : '' ?>"
          href="<?= BASE_URL ?>/finance/transaction-category/">Kategori Transaksi</a>
      <?php endif ?>
      <hr>
    <?php endif ?>
    <a class="mdl-navigation__link" href="<?= BASE_URL ?>/"><i class="material-icons">arrow_back</i>Shift Apps</a>
  </nav>
</div>