<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title">Editor Transaksi</span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="save-button"
            type="submit" name="action" value="save"><i class="material-icons left">save</i></button>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--4-col <?=
            !empty($errors['accountId']) ? 'is-invalid' : '' ?>">
            <select id="accountId" class="mdl-selectfield__select" name="accountId">
              <?php foreach ($accounts as $account): ?>
                <option value="<?= $account->id ?>" <?= $transaction->accountId == $account->id ? 'selected' : '' ?>>
                  <?= e($account->name) ?>
                </option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="accountId">Akun</label>
            <?php if (!empty($errors['accountId'])): ?>
              <span class="form-error"><?= $errors['accountId'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?=
            !empty($errors['amount']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input numberEditor" type="text" value="<?= format_number($transaction->amount) ?>"
                   maxlength="10" id="amount" name="amount">
            <label class="mdl-textfield__label" for="amount">Jumlah (Rp.)</label>
            <?php if (!empty($errors['amount'])): ?>
              <span class="form-error"><?= $errors['amount'] ?></span>
            <?php endif ?>
          </div>
        </div>
      </main>
    </form>
    <?= render('foot') ?>
  </body>
</html>