<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
    .fr{float:right;}
  </style>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Transaksi Multi Payment</span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="filter-button" type="button">
            <i class="material-icons">filter_list</i>
          </button>
          <?php if (current_user_can('topup-multipayment-account')
                    || current_user_can('adjust-multipayment-account')
                    || current_user_can('add-multipayment-account')): ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="more-button" type="button">
              <i class="material-icons">more_vert</i>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="more-button">
              <?php if (current_user_can('topup-multipayment-account')): ?>
              <li class="mdl-menu__item">
                  <a href="./editor"><i class="material-icons">add</i>Catat</a>
                </li>
              <?php endif ?>
              <?php if (current_user_can('topup-multipayment-account')): ?>
                <li class="mdl-menu__item">
                  <a href="./topup"><i class="material-icons">call_made</i>TopUp</a>
                </li>
              <?php endif ?>
              <?php if (current_user_can('adjust-multipayment-account')): ?>
                <li class="mdl-menu__item">
                  <a href="./adjust"><i class="material-icons">import_export</i>Penyesuaian</a>
                </li>
              <?php endif ?>
            </ul>
          <?php endif ?>
        </div>
      </header>
      <?= render('pos/drawer') ?>
      <main class="mdl-layout__content">
        <div id="product-list" class="mdlx-data-list">
          <?php foreach ($items as $item): ?>
            <div class="mdlx-data-list__item">
              <?php if (current_user_can('edit-multipayment-transaction')): ?>
                <a href="./editor?id=<?= $item->id ?>">
              <?php endif ?>
              <span class="fr"><b><?= format_number($item->amount) ?></b>
              </span>
                  <b><?= e($item->accountName) . ' | ' . $item->getTypeName() . ' | ' . e($item->description) ?></b>
                  <br><small><?= to_locale_datetime($item->dateTime) ?> <?= $item->getCode(); ?> <?= $item->username ?></small>
              <?php if (current_user_can('edit-multipayment-transaction')): ?>
                </a>
              <?php endif ?>
            </div>
          <?php endforeach ?>
        </div>
      </main>
    </div>
    <form method="GET">
      <dialog id="filter-dialog" class="mdl-dialog">
        <h4 class="mdl-dialog__title">Penyaringan</h4>
        <div class="mdl-dialog__content">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="accountId" name="accountId" class="mdl-selectfield__select">
              <option value="-1" <?= $filter['accountId'] === -1 ? 'selected' : '' ?>>Semua</option>
              <?php foreach ($accounts as $account): ?>
                <option value="<?= $account->id ?>" <?= $filter['accountId'] == $account->id ? 'selected' : '' ?>>
                  <?= e($account->name) ?>
                </option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="accountId">Akun</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="type" name="type" class="mdl-selectfield__select">
              <option value="-1" <?= $filter['type'] === -1 ? 'selected' : '' ?>>Semua</option>
              <?php foreach ($types as $type => $typeName): ?>
                <option value="<?= $type ?>" <?= $filter['type'] == $type ? 'selected' : '' ?>>
                  <?= $typeName ?>
                </option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="type">Jenis Transaksi</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="when" name="when" class="mdl-selectfield__select">
              <option value="anytime" <?= $filter['when'] === 'anytime' ? 'selected' : '' ?>>Kapan pun</option>
              <option value="today" <?= $filter['when'] === 'today' ? 'selected' : '' ?>>Hari Ini</option>
              <option value="yesterday" <?= $filter['when'] === 'yesterday' ? 'selected' : '' ?>>Kemarin</option>
              <option value="thisweek" <?= $filter['when'] === 'thisweek' ? 'selected' : '' ?>>Minggu Ini</option>
              <option value="prevweek" <?= $filter['when'] === 'prevweek' ? 'selected' : '' ?>>Minggu Kemarin</option>
              <option value="thismonth" <?= $filter['when'] === 'thismonth' ? 'selected' : '' ?>>Bulan Ini</option>
              <option value="prevmonth" <?= $filter['when'] === 'prevmonth' ? 'selected' : '' ?>>Bulan Kemarin</option>
            </select>
            <label class="mdl-selectfield__label" for="when">Waktu Transaksi</label>
          </div>
        </div>
        <div class="mdl-dialog__actions">
          <button type="submit" class="mdl-button apply">OK</button>
          <button type="button" class="mdl-button close">batal</button>
        </div>
      </dialog>
    </form>
    <?= render('foot') ?>
    <script>      
      var filterDialog = document.querySelector('#filter-dialog');
      if (!filterDialog.showModal) {
        dialogPolyfill.registerDialog(filterDialog);
      }
      
      document.querySelector('#filter-dialog .close').addEventListener('click', function() {
        filterDialog.close();
      });
      
      document.querySelector('#filter-button').addEventListener('click', function() {
        filterDialog.showModal();
      });
    </script>
  </body>
</html>
