<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <?php if ($transaction->id): ?>
        <input type="hidden" name="id" value="<?= $transaction->id ?>">
      <?php else: ?>
        <input type="hidden" name="accountId" value="<?= $transaction->accountId ?>">
      <?php endif ?>
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./view?id=<?= $transaction->accountId ?>" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= $transaction->id ? '#'.$transaction->id : 'Catat Transaksi Keuangan' ?></span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="save-button"
            type="submit" name="action" value="save"><i class="material-icons left">check</i></button>
          <?php if ($transaction->id && current_user_can('delete-finance-transaction')): ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="delete-button"
              type="submit" name="action" value="delete"><i class="material-icons left">delete_forever</i></button>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--2-col <?=
              !empty($errors['type']) ? 'is-invalid' : '' ?>">
            <select class="mdl-selectfield__select" id="type" name="type">
              <option value="-1">Pilih:</option>
              <option value="<?= FinanceTransaction::Income ?>" <?=
                $transaction->type == FinanceTransaction::Income  ? 'selected' : '' ?>>Pemasukan</option>
              <option value="<?= FinanceTransaction::Expense ?>" <?=
                $transaction->type == FinanceTransaction::Expense ? 'selected' : '' ?>>Pengeluaran</option>
            </select>
            <label class="mdl-selectfield__label" for="type">Jenis Transaksi</label>
            <?php if (!empty($errors['type'])): ?>
              <span class="form-error"><?= $errors['type'] ?></span>
            <?php endif ?>
          </div>
          <?php if (!empty($categories)): ?>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--4-col <?=
              !empty($errors['categoryId']) ? 'is-invalid' : '' ?>">
            <select class="mdl-selectfield__select" id="categoryId" name="categoryId">
              <option value="0">Pilih:</option>
              <?php foreach ($categories as $category): ?>
              <option value="<?= $category->id ?>" <?= $transaction->categoryId == $category->id ? 'selected' : '' ?>>
                <?= e($category->name) ?>
              </option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="categoryId">Kategori</label>
            <?php if (!empty($errors['categoryId'])): ?>
              <span class="form-error"><?= $errors['categoryId'] ?></span>
            <?php endif ?>
          </div>
          <?php endif ?>
        </div>
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
              !empty($errors['amount']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input numberEditor" type="text" value="<?= format_number(abs($transaction->amount)) ?>"
                   id="amount" name="amount">
            <label class="mdl-textfield__label" for="amount">Jumlah (Rp.)</label>
            <?php if (!empty($errors['amount'])): ?>
              <span class="form-error"><?= $errors['amount'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?=
            !empty($errors['description']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($transaction->description) ?>"
                   maxlength="40" id="description" name="description">
            <label class="mdl-textfield__label" for="description">Deskripsi</label>
            <?php if (!empty($errors['description'])): ?>
              <span class="form-error"><?= $errors['description'] ?></span>
            <?php endif ?>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['dateTime']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= date('d/m/Y H:i:s', strtotime($transaction->dateTime)) ?>"
                   id="dateTime" name="dateTime" <?= $_SESSION['CURRENT_USER']->groupId == 1 ? '' : 'readonly' ?>>
            <label class="mdl-textfield__label" for="dateTime">Waktu</label>
            <?php if (!empty($errors['dateTime'])): ?>
              <span class="form-error"><?= $errors['dateTime'] ?></span>
            <?php endif ?>
          </div>
        </div>
      </main>
    </form>
    <?= render('foot') ?>
    <script>
      confirmOnClick('#delete-button', 'Hapus transaksi?')
    </script>
  </body>
</html>