<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <input type="hidden" name="fromId" value="<?= $data->fromId ?>">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./?accountId=<?= $data->fromId ?>" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title">Transfer Kas</span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="save-button"
            type="submit" name="action" value="save"><i class="material-icons left">check</i></button>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col">
            <input class="mdl-textfield__input" type="text" value="<?= e($data->fromAccountName) ?>" readonly>
            <label class="mdl-textfield__label" for="name">Dari</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--2-col">
            <select class="mdl-selectfield__select" id="toId" name="toId">
              <?php foreach ($accounts as $account): ?>
                <option value="<?= $account->id ?>" <?= $data->toId == $account->id ? 'selected' : ''?>>
                  <?= e($account->name) ?>
                </option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="toId">Ke</label>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?=
            !empty($errors['description']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($data->description) ?>"
                   maxlength="40" id="description" name="description">
            <label class="mdl-textfield__label" for="description">Deskripsi</label>
            <?php if (!empty($errors['description'])): ?>
              <span class="form-error"><?= $errors['description'] ?></span>
            <?php endif ?>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
              !empty($errors['amount']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input numberEditor" type="text" value="<?= format_number($data->amount) ?>"
                   id="amount" name="amount">
            <label class="mdl-textfield__label" for="amount">Jumlah (Rp.)</label>
            <?php if (!empty($errors['amount'])): ?>
              <span class="form-error"><?= $errors['amount'] ?></span>
            <?php endif ?>
          </div>
        </div>
      </main>
    </form>
    <?= render('foot') ?>
  </body>
</html>