<a class="mdl-navigation__link<?= $_SERVER['PATH_INFO'] === '/service/' ? ' active' : '' ?>"
  href="<?= BASE_URL ?>/service/"><i class="material-icons">dashboard</i>Dashboard</a>
<hr>
<a class="mdl-navigation__link" href="<?= BASE_URL ?>/service/receive/">Penerimaan</a>
<a class="mdl-navigation__link" href="<?= BASE_URL ?>/service/pick/">Pengambilan</a>
<hr>
<a class="mdl-navigation__link" href="<?= BASE_URL ?>/"><i class="material-icons">arrow_back</i>Shift Apps</a>
