
<form method="POST" class="mdl-grid">
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--4-col <?=
    !empty($errors['amount']) ? 'is-invalid' : '' ?>">
    <select id="amount" name="amount" class="mdl-selectfield__select">
      <option value="0" disabled selected>Tentukan nominal:</option>
      <?php foreach ($amounts as $key => $value): ?>
        <option value="<?= $key ?>" <?= $key == $amount ? 'selected' : '' ?>><?= $value ?></option>
      <?php endforeach ?>
    </select>
    <label class="mdl-selectfield__label" for="amount">Nominal</label>
    <?php if (!empty($errors['amount'])): ?>
      <div class="form-error"><?= $errors['amount'] ?></div>
    <?php endif ?>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?=
    !empty($errors['operatorPassword']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="password" maxlength="40" id="operatorPassword" name="operatorPassword">
    <label class="mdl-textfield__label" for="operatorPassword">Kata Sandi Operator</label>
    <?php if (!empty($errors['operatorPassword'])): ?>
      <span class="form-error"><?= $errors['operatorPassword'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-cell mdl-cell--4-col buttons">
    <button type="submit" class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect">
      <div class="mdl-spinner mdl-spinner--single-color mdl-js-spinner is-active hidden" style="width:22px;height:22px;top:6px;margin-right:6px;"></div>
      <i class="material-icons">check</i>OK
    </button>
  </div>
</form>
<script>
  document.querySelector('form').addEventListener('submit', function(e) {
    document.querySelector('.mdl-spinner').classList.remove('hidden');
    document.querySelector('button .material-icons').classList.add('hidden');
    document.querySelector('button').disabled = true;
  });
</script>