<i id="server-indicator" class="material-icons">report_problem</i>
<button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="more-button">
  <i class="material-icons">more_vert</i>
</button>
<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="more-button">
  <li class="mdl-menu__item mdl-menu__item--full-bleed-divider">
    <a id="stop-action" href="#">Stop</a>
  </li>
  <li class="mdl-menu__item">
    <a id="shutdown-action" href="#">Shut Down</a>
  </li>
  <li class="mdl-menu__item">
    <a id="restart-action"a href="#">Restart</a>
  </li>
</ul>
