<a class="mdl-navigation__link<?= $_SERVER['PATH_INFO'] === '/shiftnet/client-monitor/' ? ' active' : '' ?>"
   href="<?= BASE_URL ?>/shiftnet/client-monitor/"><i class="material-icons">view_comfy</i>Client Monitor</a>
<a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/shiftnet/voucher/') ? ' active' : '' ?>"
   href="<?= BASE_URL ?>/shiftnet/voucher/"><i class="material-icons">credit_card</i>Voucher</a>
<a class="mdl-navigation__link<?= $_SERVER['PATH_INFO'] === '/shiftnet/activity/' ? ' active' : '' ?>"
   href="<?= BASE_URL ?>/shiftnet/activity/"><i class="material-icons">local_activity</i>Aktifitas</a>
<a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/shiftnet/member/') ? ' active' : '' ?>"
   href="<?= BASE_URL ?>/shiftnet/member/"><i class="material-icons">group</i>Member</a>
<hr>
<a class="mdl-navigation__link" href="<?= BASE_URL ?>/"><i class="material-icons">arrow_back</i>Shift Apps</a>