<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
    #stock-adjustment-list .detail { line-height: 14px; font-size: 12px; }
    #stock-adjustment-list .title { font-weight: bold; }
  </style>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title">Sesuaikan Stok</span>
          <div class="mdl-layout-spacer"></div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search-product-textbox"><i class="material-icons">search</i></label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" id="search-product-textbox" onkeyup="applyFilter()">
            </div>
          </div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="filter-button" type="button">
            <i class="material-icons">filter_list</i>
          </button>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="save-button" type="submit">
            <i class="material-icons">arrow_forward</i>
          </button>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdlx-data-table--responsive">
            <table id="prodct-list" class="mdl-data-table">
              <thead>
                <tr>
                  <th style="width:30px;">
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect mdl-data-table__select" for="table-header">
                      <input type="checkbox" id="table-header" class="mdl-checkbox__input" />
                    </label>
                  </th>
                  <th>Produk</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach ($items as $i => $item): ?>
                <tr>
                  <td>
                    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect mdl-data-table__select" for="row[<?= $i ?>]">
                      <input type="checkbox" id="row[<?= $i ?>]" class="mdl-checkbox__input" name="p[<?= $item->id ?>]">
                    </label>
                  </td>
                  <td><?= e($item->name) ?></td>
                </tr>
              <?php endforeach ?>
              </tbody>
            </table>
        </div>
      </main>
    </form>
    <form method="GET">
      <dialog id="filter-dialog" class="mdl-dialog">
        <h4 class="mdl-dialog__title">Penyaringan</h4>
        <div class="mdl-dialog__content">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="categoryId" class="mdl-selectfield__select" name="categoryId">
              <option value="-1" <?= $filter['categoryId'] === -1 ? 'selected' : '' ?>>Semua Kategori</option>
              <option value="0" <?= $filter['categoryId'] === 0 ? 'selected' : '' ?>>Tanpa Kategori</option>
              <?php foreach ($categories as $category): ?>
                <option value="<?= $category->id ?>" <?= $filter['categoryId'] === (int)$category->id ? 'selected' : '' ?>><?= e($category->name) ?></option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="categoryId">Kategori</label>
          </div>
        </div>
        <div class="mdl-dialog__actions">
          <button type="submit" class="mdl-button apply">OK</button>
          <button type="button" class="mdl-button close">batal</button>
        </div>
      </dialog>
    </form>
    <?= render('foot') ?>
    <script>
      function applyFilter() {
        var input, filter, rows, productNameElement, i;
        input = document.getElementById("search-product-textbox");
        filter = input.value.toUpperCase();
        rows = document.querySelectorAll("#prodct-list tbody tr");

        for (i = 0; i < rows.length; i++) {
          productNameElement = rows[i].children[1];
          if (productNameElement) {
            if (productNameElement.innerHTML.toUpperCase().indexOf(filter) > -1) {
              rows[i].style.display = "";
            } else {
              rows[i].style.display = "none";
            }
          } 
        }
      }
      
      // checkbox handler
      var table = document.querySelector('table');
      var headerCheckbox = table.querySelector('thead .mdl-data-table__select input');
      var boxes = table.querySelectorAll('tbody .mdl-data-table__select');
      var headerCheckHandler = function(event) {
        if (event.target.checked) {
          for (var i = 0, length = boxes.length; i < length; i++) {
            boxes[i].MaterialCheckbox.check();
          }
        } else {
          for (var i = 0, length = boxes.length; i < length; i++) {
            boxes[i].MaterialCheckbox.uncheck();
          }
        }
      };
      headerCheckbox.addEventListener('change', headerCheckHandler);

      // filter handler
      var filterDialog = document.querySelector('#filter-dialog');
      if (! filterDialog.showModal) {
        dialogPolyfill.registerDialog(filterDialog);
      }
      
      document.querySelector('#filter-dialog .close').addEventListener('click', function() {
        filterDialog.close();
      });
      
      document.querySelector('#filter-button').addEventListener('click', function() {
        filterDialog.showModal();
      });
    </script>
  </body>
</html>