<style>
  td .mdl-textfield{margin:0;padding:0;width:80px;}
</style>
<form method="POST" class="mdl-grid" id="editor">
  <input type="hidden" name="id" value="<?= $data->id ?>">
  <?php if ($data->status != 1): ?>
  <div class="mdl-cell mdl-cell--12-col buttons" style="min-height:0;margin-bottom:20px;">
    <?php if ($data->status == 0): ?>
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit"
            name="action" value="save"><i class="material-icons">save</i> Simpan</button>
    <button class="mdl-button mdl-button--raised mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit"
            name="action" value="complete"><i class="material-icons">check</i> Selesai</button>
    <button class="mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect" type="submit"
            name="action" value="cancel"><i class="material-icons">delete</i> Batalkan</button>
    <?php elseif ($data->status == 2): ?>
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit"
        name="action" value="delete"><i class="material-icons">delete_forever</i> Hapus</button>
    <?php endif ?>
  </div>
  <?php endif ?>
  <div class="mdl-cell mdl-cell--12-col">
    <table>
      <tr>
        <td>Waktu</td>
        <td>:</td>
        <td><?= date('d/m/Y H:i:s', strtotime($data->dateTime)) ?></td>
        <td style="width:20px;"></td>
        <td>Status</td>
        <td>:</td>
        <td><?= $data->status == 0 ? 'Disimpan' : ($data->status == 1 ? 'Selesai' : 'Dibatalkan') ?></td>
      </tr>
      <tr>
        <td>Selisih Modal</td>
        <td>:</td>
        <td><?= format_money($data->totalCost) ?></td>
        <td></td>
        <td>Selisih Harga</td>
        <td>:</td>
        <td><?= format_money($data->totalPrice) ?></td>
      </tr>
    </table>
  </div>
  <div class="mdlx-data-table--responsive mdl-cell mdl-cell--12-col">
    <table class="mdl-data-table">
      <thead>
        <tr>
          <th>Nama Produk</th>
          <th>Stok Tercatat</th>
          <th>Stok Aktual</th>
          <th>Selisih</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($data->items as $i => $item): ?>
        <tr data-item-id="<?= $item->id ?>">
          <td><?= e($item->name) ?></td>
          <td data-stock="<?= $item->stock ?>"><?= format_number($item->stock) . ' ' . $item->uom ?></td>
          <td>
            <?php if ($data->status == 0): ?>
            <div class="mdl-textfield mdl-js-textfield">
              <input class="mdl-textfield__input" type="number" min="0" id="item-<?= $i ?>" name="i[<?= $item->id ?>]" value="<?= $item->quantity ?>">
              <label class="mdl-textfield__label" for="item-<?= $i ?>"></label>
            </div>
            <?php else: ?>
            <?= format_number($item->quantity) ?>
            <?php endif ?>
          </td>
          <td><?= format_number($item->quantity - $item->stock) ?></td>
        </tr>
      <?php endforeach ?>
      </tbody>
    </table>
  </div>
</form>
<script>
  document.querySelectorAll('#editor tbody input').forEach(function(input) {
    input.addEventListener('change', function() {
      var row = input.parentElement.parentElement.parentElement;
      var a = row.children[1].getAttribute('data-stock');
      var b = input.value;
      row.children[3].innerHTML = b - a;
      
    });
  });
</script>
