<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
    .mdl-textfield { margin: 0; padding: 0; width: 40px; }
    .mdl-textfield__input { text-align: center; font-size: 13px; }
    #item-editor tr > * { text-align: center; }
    #item-editor tr > *:nth-child(1) { text-align: left; }
    @media (max-width: 640px) {
      #item-editor tr > *:nth-child(2),
      #item-editor tr > *:nth-child(4) { display: none };
    }
  </style>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title">#<?= format_stock_adjustment_code($data->id) ?></span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" type="submit" name="action" value="print">
            <i class="material-icons">print</i>
          </button>          
          <?php if ($data->status == 0): ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" type="submit" name="action" value="save">
              <i class="material-icons">save</i>
            </button>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="more-button" type="button">
              <i class="material-icons">more_vert</i>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="more-button">
              <li class="mdl-menu__item">
                <button id="complete-button" type="submit" name="action" value="complete"><i class="material-icons">check</i> Selesai</button>
              </li>
              <li class="mdl-menu__item">
                <button id="cancel-button" type="submit" name="action" value="cancel"><i class="material-icons">delete</i> Batalkan</button>
              </li>
            </ul>
          <?php else: ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="more-button" type="button">
              <i class="material-icons">more_vert</i>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="more-button">
              <li class="mdl-menu__item">
                <button id="delete-button" type="submit" name="action" value="delete"><i class="material-icons">delete_forever</i> Hapus</button>
              </li>
            </ul>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <h5 class="mdl-cell mdl-cell--12-col">Informasi Umum</h5>
          <input type="hidden" name="id" value="<?= $data->id ?>">
          <div class="mdl-cell mdl-cell--12-col">
            <table>
              <tr>
                <td>Status</td>
                <td>:</td>
                <td><?= $data->status == 0 ? 'Disimpan' : ($data->status == 1 ? 'Selesai' : 'Dibatalkan') ?></td>
              </tr>
              <tr>
                <td>Selisih</td>
                <td>:</td>
                <td><?= format_money($data->totalCost) ?> / <?= format_money($data->totalPrice) ?></td>
              </tr>
            </table>
          </div>
          <p class="mdl-cell mdl-cell--12-col">Terakhir kali disimpan pada <?= date('d/m/Y H:i:s', strtotime($data->dateTime)) ?></p>
          <div id="item-editor" class="mdlx-data-table--responsive mdl-cell mdl-cell--12-col">
            <table class="mdl-data-table condensed">
              <thead>
                <tr>
                  <th>Nama Produk</th>
                  <th>Tercatat</th>
                  <th>Aktual</th>
                  <th>Selisih</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach ($data->items as $i => $item): ?>
                <tr>
                  <td><?= e($item->name) ?></td>
                  <td><?= format_number($item->stock) . ' ' . $item->uom ?></td>
                  <td>
                    <?php if ($data->status == 0): ?>
                    <div class="mdl-textfield mdl-js-textfield">
                      <input class="mdl-textfield__input" type="number" step="1" id="item-<?= $i ?>" name="i[<?= $item->id ?>]" value="<?= $item->quantity ?>"
                             onfocus="this.select();" pattern="\d{1,5}">
                      <label class="mdl-textfield__label" for="item-<?= $i ?>"></label>
                    </div>
                    <?php else: ?>
                    <?= format_number($item->quantity) ?>
                    <?php endif ?>
                  </td>
                  <td><?= format_number($item->quantity - $item->stock) ?></td>
                </tr>
              <?php endforeach ?>
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </form>
    <?= render('foot') ?>
    <script>
      document.querySelectorAll('#item-editor tbody input').forEach(function(input) {
        input.addEventListener('keyup', function() {
          var actualQuantity = parseInt(input.value);
          var row = input.parentElement.parentElement.parentElement;
          var storedQuantity = row.children[1].innerHTML.split(' ')[0];
          if (isNaN(actualQuantity))
            row.children[3].innerHTML = '?';
          else
            row.children[3].innerHTML = actualQuantity - storedQuantity;
        })
      });
      
      var deleteButton = document.querySelector('#delete-button');
      if (deleteButton) {
        deleteButton.addEventListener('click', function(e) {
          if (!confirm('Hapus Penyesuaian Stok?')) {
            e.preventDefault();
            return;
          }
        });
      }
      
      var completeButton = document.querySelector('#complete-button');
      if (completeButton) {
        completeButton.addEventListener('click', function(e) {
          if (!confirm('Penyesuaian Stok telah selesai?')) {
            e.preventDefault();
            return;
          }
        });
      }
      
      var cancelButton = document.querySelector('#cancel-button');
      if (cancelButton) {
        cancelButton.addEventListener('click', function(e) {
          if (!confirm('Batalkan penyesuaian stok?')) {
            e.preventDefault();
            return;
          }
        });
      }
    </script>
  </body>
</html>