<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
  </style>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Dasbor POS</span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </header>
      <?= render('pos/drawer') ?>
      <main class="mdl-layout__content">
      </main>
    </div>
    <?= render('foot') ?>
  </body>
</html>
