<div class="mdl-layout__drawer">
  <header class="mdl-color--blue-grey mdl-color-text--white">
    <span class="mdl-layout-title"><small><?= 'Point of Sales' ?></small></span>
    <span class="my-account-name"><a class="mdl-color-text--white" href="<?= BASE_URL ?>/account"><?= $_SESSION['CURRENT_USER']->username ?></a></span>
  </header>
  <nav class="mdl-navigation">
    <a class="mdl-navigation__link<?= $_SERVER['PATH_INFO'] == BASE_URL . '/pos/' ? ' active' : '' ?>"
       href="<?= BASE_URL ?>/pos/"><i class="material-icons">dashboard</i>Dasbor</a>
    <hr>
    <?php if (current_user_can('view-reports')): ?>
      <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/report/') ? ' active' : '' ?>"
        href="<?= BASE_URL ?>/pos/report/">Laporan</a>
      <hr>
    <?php endif ?>
    <?php if (current_user_can('view-sales-orders')): ?>
      <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/sales-order/') ? ' active' : '' ?>"
        href="<?= BASE_URL ?>/pos/sales-order/">Penjualan</a>
      <hr>
    <?php endif ?>
    <?php if (current_user_can('view-purchasing-orders')): ?>
      <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/purchasing-order/') ? ' active' : '' ?>"
        href="<?= BASE_URL ?>/pos/purchasing-order/">Pembelian</a>
      <hr>
    <?php endif ?>
    <?php if (current_user_can('view-multipayment-transactions') || current_user_can('view-multipayment-accounts')): ?>
      <?php if (current_user_can('view-multipayment-transactions')): ?>
        <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/multipayment-transaction/') ? ' active' : '' ?>"
          href="<?= BASE_URL ?>/pos/multipayment-transaction/">Transaksi Multi Payment</a>
      <?php endif ?>
      <?php if (current_user_can('view-multipayment-accounts')): ?>
        <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/multipayment-account/') ? ' active' : '' ?>"
          href="<?= BASE_URL ?>/pos/multipayment-account/">Akun Multi Payment</a>
      <?php endif ?>
      <hr>
    <?php endif ?>
    <?php if (current_user_can('view-stock-adjustments') || current_user_can('view-products')): ?>
      <?php if (current_user_can('view-stock-adjustments')): ?>
        <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/stock-adjustment/') ? ' active' : '' ?>"
          href="<?= BASE_URL ?>/pos/stock-adjustment/">Penyesuaian Stok</a>
      <?php endif ?>
      <?php if (current_user_can('view-products')): ?>
        <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/product/') ? ' active' : '' ?>"
          href="<?= BASE_URL ?>/pos/product/">Produk</a>
      <?php endif ?>
      <?php if (current_user_can('view-product-categories')): ?>
        <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/product-category/') ? ' active' : '' ?>"
          href="<?= BASE_URL ?>/pos/product-category/">Kategori Produk</a>
      <?php endif ?>
      <hr>
    <?php endif ?>
    <a class="mdl-navigation__link" href="<?= BASE_URL ?>/"><i class="material-icons">arrow_back</i>Shift Apps</a>
  </nav>
</div>