<div class="mdl-grid">
  <?php if (count($products) == 0 ): ?>
    <p class="mdl-cell mdl-cell--12-col">Tidak ada produk.</p>
  <?php else: ?>
    <style>
      .mdl-data-table>thead th:nth-child(2) { text-align: right; }
      .mdl-data-table tbody tr,
      .mdl-data-table td{
        height: auto;
      }
      .mdl-data-table th { text-align: left; }
      .mdl-data-table >tbody>tr> td {
        padding-top: 5px;
        padding-bottom: 5px;
        vertical-align: top;
        text-align: left;
      }

      .inner-table {width:100%;}
      #price-list-table .inner-table td {
        border: none;
        padding: 0;
        text-align: right;
      }
      #price-list-table .inner-table td:nth-child(1) { width: 100px; padding-right: 10px; }
    </style>
    <div class="mdl-cell mdl-cell--12-col mdlx-data-table--responsive">
      <table id="price-list-table" class="mdl-data-table">
        <thead>
          <tr>
            <th>Produk</th>
            <th>Harga</th>
            <th>Stok</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($products as $product): ?>
          <tr>
            <td><?= e($product->name) ?></td>
            <td>
              <table class="inner-table">
              <?php for ($i = 0; $i < count($product->priceInfo); $i++): ?>
                <tr>
                  <td><?= $product->priceInfo[$i][0] ?></td>
                  <td><?= $product->priceInfo[$i][1] ?></td>
                </tr>
              <?php endfor ?>
              </table>
            </td>
            <td><?= $product->stockInfo ?></td>
          </tr>
          <?php endforeach ?>
          <tr style="display:none;" id="empty-result-info">
            <td colspan="3" style="text-align:center;font-style:italic;">Tidak ditemukan</td>
          </tr>
        </tbody>
      </table>
    </div>
    <script>
      function applyFilter() {   
        var input, filter, table, rows, td, i;
        input = document.getElementById("search-product-textbox");
        filter = input.value.toUpperCase();
        table = document.querySelector("#price-list-table>tbody");
        rows = table.querySelectorAll("#price-list-table>tbody>tr");
        var visibleItemCount = rows.length - 1;
        for (i = 0; i < rows.length - 1; i++) {
          td = rows[i].children[0];
          if (td) {
            if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
              rows[i].style.display = "";
            } else {
              rows[i].style.display = "none";
              visibleItemCount--;
            }
          } 
        }
        document.getElementById('empty-result-info').style.display = visibleItemCount === 0 ? '' : 'none';
      }
    </script>
  <?php endif ?>  
</div>