<div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right">
  <label class="mdl-button mdl-js-button mdl-button--icon" for="search-product-textbox"><i class="material-icons">search</i></label>
  <div class="mdl-textfield__expandable-holder">
    <input class="mdl-textfield__input" type="text" id="search-product-textbox" onkeyup="applyFilter()">
  </div>
</div>
