<div class="mdl-grid table-container">
  <?php if (count($products) == 0 ): ?>
    <p class="mdl-cell mdl-cell--12-col">Tidak ada produk.</p>
  <?php else: ?>
    <div class="mdl-cell mdl-cell--12-col mdlx-data-table--responsive">
      <table id="price-list-table" class="mdl-data-table">
        <thead>
          <tr>
            <th>Produk</th>
            <th>Stok</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($products as $product): ?>
          <tr>
            <td>
              <b><?= e($product->name) ?><br></b>
              <?= $product->getPriceInfo() ?>
            </td>
            <td><?= $product->getStockInfo() ?></td>
          </tr>
          <?php endforeach ?>
          <tr style="display:none;" id="empty-result-info">
            <td colspan="3" style="text-align:center;font-style:italic;">Tidak ditemukan</td>
          </tr>
        </tbody>
      </table>
    </div>
    <script>
      function applyFilter() {   
        var input, filter, table, rows, td, i;
        input = document.getElementById("search-product-textbox");
        filter = input.value.toUpperCase();
        table = document.querySelector("#price-list-table>tbody");
        rows = table.querySelectorAll("#price-list-table>tbody>tr");
        var visibleItemCount = rows.length - 1;
        for (i = 0; i < rows.length - 1; i++) {
          td = rows[i].children[0];
          if (td) {
            if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
              rows[i].style.display = "";
            } else {
              rows[i].style.display = "none";
              visibleItemCount--;
            }
          } 
        }
        document.getElementById('empty-result-info').style.display = visibleItemCount === 0 ? '' : 'none';
      }
    </script>
  <?php endif ?>  
</div>
