<a class="mdl-navigation__link<?= $_SERVER['PATH_INFO'] === '/pos/price-list' ? ' active' : '' ?>"
  href="<?= BASE_URL ?>/pos/price-list">Daftar Harga</a>
<a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/sales-order/') ? ' active' : '' ?>"
  href="<?= BASE_URL ?>/pos/sales-order/">Penjualan</a>
<?php if ($_SESSION['CURRENT_USER']->groupId == 1) : ?>
  <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/purchasing-order/') ? ' active' : '' ?>"
    href="<?= BASE_URL ?>/pos/purchasing-order/">Pembelian</a>
  <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/stock-adjustment/') ? ' active' : '' ?>"
    href="<?= BASE_URL ?>/pos/stock-adjustment/">Penyesuaian Stok</a>
  <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/product/') ? ' active' : '' ?>"
    href="<?= BASE_URL ?>/pos/product/">Produk</a>
<?php endif ?>
<hr>
<a class="mdl-navigation__link" href="<?= BASE_URL ?>/"><i class="material-icons">arrow_back</i>Shift Apps</a>
