<a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/sales-order/') ? ' active' : '' ?>"
  href="<?= BASE_URL ?>/pos/sales-order/">Penjualan</a>
<a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/purchasing-order/') ? ' active' : '' ?>"
  href="<?= BASE_URL ?>/pos/purchasing-order/">Pembelian</a>
<hr>
<a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/stock-adjustment/') ? ' active' : '' ?>"
  href="<?= BASE_URL ?>/pos/stock-adjustment/">Penyesuaian Stok</a>
<a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/product/') ? ' active' : '' ?>"
  href="<?= BASE_URL ?>/pos/product/">Produk</a>
<a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/pos/product-category/') ? ' active' : '' ?>"
  href="<?= BASE_URL ?>/pos/product-category/">Kategori Produk</a>
<hr>
<a class="mdl-navigation__link" href="<?= BASE_URL ?>/"><i class="material-icons">arrow_back</i>Shift Apps</a>
