<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= !$item->id ? 'Tambah' : 'Edit' ?> Biaya</span>
          <div class="mdl-layout-spacer"></div>
          <?php if (!$item->id || ($item->id && $_SESSION['CURRENT_USER']->groupId == 1)): ?>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="save-button"
            type="submit" name="action" value="save"><i class="material-icons left">save</i></button>
          <?php endif ?>
          <?php if ($item->id && $_SESSION['CURRENT_USER']->groupId != 1): ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="more-button" type="button">
              <i class="material-icons">more_vert</i>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="more-button">
              <li class="mdl-menu__item">
                <button id="delete-button" type="submit" name="action" value="delete"><i class="material-icons left">delete</i> Hapus</button>
              </li>
            </ul>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <?php if ($item->id): ?>
            <input type="hidden" name="id" value="<?= $item->id ?>">
          <?php endif ?>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--4-col">
            <select class="mdl-selectfield__select" id="categoryId" name="categoryId">
              <?php foreach ($categories as $category): ?>
                <option value="<?= $category->id ?>" <?= $item->categoryId == $category->id ? 'selected' : '' ?>><?= e($category->name) ?></option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="categoryId">Kategori</label>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--8-col <?=
            !empty($errors['description']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->description) ?>" maxlength="100" id="description" name="description">
            <label class="mdl-textfield__label" for="description">Deskripsi</label>
            <?php if (!empty($errors['description'])): ?>
              <span class="form-error"><?= $errors['description'] ?></span>
            <?php endif ?>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['amount']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input numberEditor" type="text" value="<?= format_number($item->amount) ?>" 
                   maxlength="10" id="amount" name="amount">
            <label class="mdl-textfield__label" for="amount">Jumlah (Rp.)</label>
            <?php if (!empty($errors['amount'])): ?>
              <span class="form-error"><?= $errors['amount'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['ref']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->ref) ?>" maxlength="100" id="ref" name="ref">
            <label class="mdl-textfield__label" for="ref">No. Bukti / Referensi</label>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['dateTime']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= date('d/m/Y H:i:s', strtotime($item->dateTime)) ?>" id="dateTime" name="dateTime"
                   <?= $_SESSION['CURRENT_USER']->groupId == 1 ? '' : 'readonly' ?>>
            <label class="mdl-textfield__label" for="dateTime">Waktu</label>
            <?php if (!empty($errors['dateTime'])): ?>
              <span class="form-error"><?= $errors['dateTime'] ?></span>
            <?php endif ?>
          </div>
        </div>
        <?php if ($item->id): ?>
        <div class="mdl-grid">
          <div class="mdl-cell mdl-cell--12-col">
            <p>
              Dibuat oleh <?= e($item->creationUsername) ?>, <?= to_locale_datetime($item->creationDateTime) ?>
              <br>Diperbarui terakhir kali oleh <?= e($item->lastModUsername) ?>, <?= to_locale_datetime($item->lastModDateTime) ?>
            </p>
          </div>
        </div>
        <?php endif ?>
      </main>
    </form>
    <?= render('foot') ?>
    <script>
      var deleteButton = document.querySelector('#delete-button');
      if (deleteButton) {
        deleteButton.addEventListener('click', function(e) {
          if (!confirm('Hapus Kategori?')) {
            e.preventDefault();
            return;
          }
        });
      }
    </script>
  </body>
</html>