<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
  </style>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Biaya Operasional (<?= count($items) ?>)</span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="filter-button" type="button">
            <i class="material-icons">filter_list</i>
          </button>
          <a href="./editor" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">add</i>
          </a>
        </div>
      </header>
      <?= render('finance/drawer') ?>
      <main class="mdl-layout__content">
        <div id="operational-cost-list" class="mdlx-data-list">
          <?php foreach ($items as $item): ?>
            <div class="mdlx-data-list__item">
              <a href="./editor?id=<?= $item->id ?>">
                <?= '#' . format_operational_cost_code($item->id) . ' ' . to_locale_datetime($item->dateTime) ?>
                <span style="float:right;"><?= format_money($item->amount) ?></span>
                <br><?= e($item->categoryName) . ': ' . e($item->description) ?>
                <?= $item->ref ? '<br>Ref: ' . e($item->ref) : '' ?>
              </a>
            </div>
          <?php endforeach ?>
        </div>
      </main>
    </div>
    <form method="GET">
      <dialog id="filter-dialog" class="mdl-dialog">
        <h4 class="mdl-dialog__title">Penyaringan</h4>
        <div class="mdl-dialog__content">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="categoryId" class="mdl-selectfield__select" name="categoryId">
              <option value="-1" <?= $filter['categoryId'] === -1 ? 'selected' : '' ?>>Semua Kategori</option>
              <?php foreach ($categories as $category): ?>
                <option value="<?= $category->id ?>" <?= $filter['categoryId'] === (int)$category->id ? 'selected' : '' ?>><?= e($category->name) ?></option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="categoryId">Kategori</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="date" name="date" class="mdl-selectfield__select">
              <option value="anytime" <?= $filter['date'] === 'anytime' ? 'selected' : '' ?>>Kapan Saja</option>
              <option value="today" <?= $filter['date'] === 'today' ? 'selected' : '' ?>>Hari Ini</option>
              <option value="yesterday" <?= $filter['date'] === 'yesterday' ? 'selected' : '' ?>>Kemarin</option>
              <option value="thisweek" <?= $filter['date'] === 'thisweek' ? 'selected' : '' ?>>Minggu Ini</option>
              <option value="prevweek" <?= $filter['date'] === 'prevweek' ? 'selected' : '' ?>>Minggu Kemarin</option>
              <option value="thismonth" <?= $filter['date'] === 'thismonth' ? 'selected' : '' ?>>Bulan Ini</option>
              <option value="prevmonth" <?= $filter['date'] === 'prevmonth' ? 'selected' : '' ?>>Bulan Kemarin</option>
            </select>
            <label class="mdl-selectfield__label" for="date">Tanggal</label>
          </div>
        </div>
        <div class="mdl-dialog__actions">
          <button type="submit" class="mdl-button apply">OK</button>
          <button type="button" class="mdl-button close">batal</button>
        </div>
      </dialog>
    </form>
    <?= render('foot') ?>
    <script>      
      var filterDialog = document.querySelector('#filter-dialog');
      if (!filterDialog.showModal) {
        dialogPolyfill.registerDialog(filterDialog);
      }
      
      document.querySelector('#filter-dialog .close').addEventListener('click', function() {
        filterDialog.close();
      });
      
      document.querySelector('#filter-button').addEventListener('click', function() {
        filterDialog.showModal();
      });
    </script>
  </body>
</html>
