<a class="mdl-navigation__link<?= $_SERVER['PATH_INFO'] === '/report/balance-sheet' ? ' active' : '' ?>"
   href="<?= BASE_URL ?>/report/balance-sheet"><i class="material-icons">monetization_on</i>Neraca</a>
<hr>
<a class="mdl-navigation__link<?= $_SERVER['PATH_INFO'] === '/report/sales/' ? ' active' : '' ?>"
   href="<?= BASE_URL ?>/report/sales/">Laporan Penjualan</a>
<a class="mdl-navigation__link<?= $_SERVER['PATH_INFO'] === '/' ? ' active' : '' ?>"
   href="<?= BASE_URL ?>/"><i class="material-icons">apps</i>Apps</a>
