<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <?php if ($item->id): ?>
        <input type="hidden" name="id" value="<?= $item->id ?>">
      <?php endif ?>
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= !$item->id ? 'Buat Akun Kredit' : $item->getCode() ?></span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="save-button"
            type="submit" name="action" value="save"><i class="material-icons left">check</i></button>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?=
            !empty($errors['customerName']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->customerName) ?>" maxlength="100"
                   id="name" name="customerName">
            <label class="mdl-textfield__label" for="customerName">Nama Nasabah</label>
            <?php if (!empty($errors['customerName'])): ?>
              <span class="form-error"><?= $errors['customerName'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['customerId']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->customerId) ?>" maxlength="40"
                   id="customerId" name="customerId">
            <label class="mdl-textfield__label" for="customerId">No. KTP</label>
            <?php if (!empty($errors['customerId'])): ?>
              <span class="form-error"><?= $errors['customerId'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['customerContact']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->customerContact) ?>" maxlength="40"
                   id="customerContact" name="customerContact">
            <label class="mdl-textfield__label" for="customerContact">Kontak</label>
            <?php if (!empty($errors['customerContact'])): ?>
              <span class="form-error"><?= $errors['customerContact'] ?></span>
            <?php endif ?>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--8-col <?=
            !empty($errors['customerAddress']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->customerAddress) ?>" maxlength="100"
                   id="customerAddress" name="customerAddress">
            <label class="mdl-textfield__label" for="customerAddress">Alamat</label>
            <?php if (!empty($errors['customerAddress'])): ?>
              <span class="form-error"><?= $errors['customerAddress'] ?></span>
            <?php endif ?>
          </div>
        </div>
        <div class="mdl-grid">
          <datalist id="credit-product-list">
            <option>OPPO A37</option>
            <option>OPPO A39</option>
            <option>OPPO F1S 32GB</option>
            <option>OPPO F1S 64GB</option>
            <option>Vivo Y21</option>
            <option>Vivo Y51L</option>
            <option>Vivo Y55</option>
            <option>Vivo Y55S</option>
            <option>Vivo V5 Lite</option>
            <option>Vivo V5</option>
          </datalist>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['productName']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->productName) ?>" maxlength="40"
                   id="productName" name="productName" list="credit-product-list">
            <label class="mdl-textfield__label" for="productName">Produk</label>
            <?php if (!empty($errors['productName'])): ?>
              <span class="form-error"><?= $errors['productName'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['productPrice']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input numberEditor" type="text" value="<?= format_number($item->productPrice) ?>" maxlength="15"
                   id="productPrice" name="productPrice">
            <label class="mdl-textfield__label" for="productPrice">Harga (Rp.)</label>
            <?php if (!empty($errors['productPrice'])): ?>
              <span class="form-error"><?= $errors['productPrice'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['administrationCost']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input numberEditor" type="text" value="<?= format_number($item->administrationCost) ?>"
                   maxlength="100" id="administrationCost" name="administrationCost">
            <label class="mdl-textfield__label" for="administrationCost">Biaya Administrasi (Rp.)</label>
            <?php if (!empty($errors['administrationCost'])): ?>
              <span class="form-error"><?= $errors['administrationCost'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['productSerialNumber']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->productSerialNumber) ?>" maxlength="40"
                   id="productSerialNumber" name="productSerialNumber">
            <label class="mdl-textfield__label" for="productSerialNumber">SN / IMEI</label>
            <?php if (!empty($errors['productSerialNumber'])): ?>
              <span class="form-error"><?= $errors['productSerialNumber'] ?></span>
            <?php endif ?>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--2-col">
            <select id="referralId" class="mdl-selectfield__select" name="referralId">
              <?php foreach ($referrals as $referral): ?>
                <option value="<?= $referral->id ?>" <?= $referral->id == $item->referralId ? 'selected' : '' ?>>
                  <?= e($referral->name) ?>
                </option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="referralId">Referal</label>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['dueDate']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="number" min="1" max="27" value="<?= $item->dueDate ?>" maxlength="2"
                   id="dueDate" name="dueDate">
            <label class="mdl-textfield__label" for="dueDate">Tgl Jatuh Tempo</label>
            <?php if (!empty($errors['dueDate'])): ?>
              <span class="form-error"><?= $errors['dueDate'] ?></span>
            <?php endif ?>
          </div>
        </div>
      </main>
    </form>
    <?= render('foot') ?>
  </body>
</html>