<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= $item->getCode() ?></span>
          <div class="mdl-layout-spacer"></div>
          <?php if (current_user_can('add-credit-transaction')): ?>
            <a class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="add-button"
               href="../transaction/editor?accountId=<?= $item->id ?>"><i class="material-icons left">add</i></a>
          <?php endif ?>
          <?php if (current_user_can('edit-credit-account') || current_user_can('delete-credit-account')): ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="more-button" type="button">
              <i class="material-icons">more_vert</i>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="more-button">
              <?php if (current_user_can('edit-credit-account')): ?>
                <li class="mdl-menu__item">
                  <a href="./editor?id=<?= $item->id ?>"><i class="material-icons">edit</i> Edit</a>
                </li>
              <?php endif ?>
              <?php if (current_user_can('delete-credit-account')): ?>
                <li class="mdl-menu__item">
                  <button id="delete-button" type="submit" name="action" value="delete"><i class="material-icons">delete_forever</i> Hapus</button>
                </li>
              <?php endif ?>
            </ul>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-cell--4-col">
            <h5>Informasi Nasabah</h5>
            <table>
              <tr>
                <td>Nama</td>
                <td>:</td>
                <td><?= e($item->customerName) ?></td>
              </tr>
              <?php if (!empty($item->customerId)): ?>
              <tr>
                <td>No. KTP</td>
                <td>:</td>
                <td><?= e($item->customerId) ?></td>
              </tr>
              <?php endif ?>
              <?php if (!empty($item->customerAddress)): ?>
              <tr>
                <td>Alamat</td>
                <td>:</td>
                <td><?= e($item->customerAddress) ?></td>
              </tr>
              <?php endif ?>
              <?php if (!empty($item->customerContact)): ?>
              <tr>
                <td>Kontak</td>
                <td>:</td>
                <td><?= e($item->customerContact) ?></td>
              </tr>
              <?php endif ?>
            </table>
          </div>
          <div class="mdl-cell--4-col">
            <h5>Informasi Produk</h5>
            <table>
              <tr>
                <td>Produk</td>
                <td>:</td>
                <td><?= e($item->productName) ?></td>
              </tr>
              <tr>
                <td>Harga (Rp.)</td>
                <td>:</td>
                <td><?= format_number($item->productPrice) ?></td>
              </tr>
              <?php if (!empty($item->productSerialNumber)): ?>
              <tr>
                <td>SN/IMEI</td>
                <td>:</td>
                <td><?= e($item->productSerialNumber) ?></td>
              </tr>
              <?php endif ?>
            </table>
          </div>
          <div class="mdl-cell--4-col">
            <h5>Informasi Kredit</h5>
            <table>
              <tr>
                <td>Status</td>
                <td>:</td>
                <td><?= $item->balance == 0 ? 'Lunas' : 'Belum Lunas' ?></td>
              </tr>
              <tr>
                <td>Referal</td>
                <td>:</td>
                <td><?= e($item->referralName) ?></td>
              </tr>
              <tr>
                <td>Jatuh Tempo</td>
                <td>:</td>
                <td>Tgl. <?= $item->dueDate ?></td>
              </tr>
              <?php if (!empty($item->administrationCost)): ?>
              <tr>
                <td>Biaya Adm (Rp.)</td>
                <td>:</td>
                <td><?= format_number($item->administrationCost) ?></td>
              </tr>
              <?php endif ?>
              <tr>
                <td>Total (Rp.)</td>
                <td>:</td>
                <td><?= format_number($item->productPrice + $item->administrationCost) ?></td>
              </tr>
              <tr>
                <td>Sisa (Rp.)</td>
                <td>:</td>
                <td><?= format_number($item->balance) ?></td>
              </tr>
            </table>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-cell mdl-cell--12-col">
            <h5>Penerimaan Angsuran</h5>
            <?php if (empty($item->transactions)): ?>
              <p>Belum ada penerimaan angsuran.</p>
            <?php else: ?>
            <div class="mdlx-data-table--responsive">
              <table class="mdl-data-table condensed">
                <thead>
                  <tr>
                    <th>Tanggal</th>
                    <th>Jenis</th>
                    <th>Jumlah (Rp.)</th>
                  </tr>
                </thead>
                <tbody>
                <?php foreach ($item->transactions as $transaction): ?>
                  <tr>
                    <td>
                      <?php if (current_user_can('edit-credit-transaction')): ?>
                        <a href="../transaction/editor?id=<?= $transaction->id ?>">
                      <?php endif ?>
                      <small>
                        <?= $item->getCode() ?>
                        <br><?= date('d/m/Y', strtotime($transaction->dateTime)) ?>
                      </small>
                      <?php if (current_user_can('edit-credit-transaction')): ?>
                        </a>
                      <?php endif ?>
                    </td>
                    <td>
                      <?= $transaction->types == 0 ? 'Biaya Adm' : ($transaction->types == 1 ? 'Biaya Adm' : 'Biaya Adm dan Angsuran') ?>
                    </td>
                    <td><?= format_number($transaction->amount) ?>
                  </tr>
                <?php endforeach ?>
                </tbody>
              </table>
            </div>
            <?php endif ?>
          </div>
        </div>
      </main>
    </div>
    <?= render('foot') ?>
    <script>
      confirmOnClick('#delete-button', 'Hapus akun?');
    </script>
  </body>
</html>