<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= $item->getCode() ?></span>
          <div class="mdl-layout-spacer"></div>
          <?php if (current_user_can('edit-credit-account')): ?>
          <a class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="edit-button"
            href="./editor?id=<?= $item->id ?>"><i class="material-icons left">edit</i></a>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-cell--12-col">
            
          </div>
        </div>
      </main>
    </div>
    <?= render('foot') ?>
    <script>
      confirmOnClick('#delete-button', 'Hapus referal?');
    </script>
  </body>
</html>