<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./editor?id=<?= $item->parentId ?>" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= format_purchasing_order_code($item->parentId) ?></span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="save-button"
            type="submit" name="action" value="save"><i class="material-icons left">check</i></button>
          <?php if ($item->id): ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="delete-button" type="submit" name="action" value="delete">
              <i class="material-icons left">delete</i>
            </button>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <?php if ($item->id): ?>
            <input type="hidden" name="id" value="<?= $item->id ?>">
          <?php endif ?>
          <input type="hidden" name="parentId" value="<?= $item->parentId ?>">
          <input type="hidden" id="productId" name="productId" value="<?= $item->productId ?>">
          <datalist id="product-list">
            <?php foreach ($products as $product): ?>
              <option value="<?= e($product->name) ?>">
            <?php endforeach; ?>
          </datalist>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?= !empty($errors['productId']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($item->productName) ?>" id="productName" name="productName" list="product-list">
            <label class="mdl-textfield__label" for="productName">Produk</label>
            <?php if (!empty($errors['productId'])): ?>
              <span class="form-error"><?= $errors['productId'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?= !empty($errors['quantity']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input numberEditor" type="text" value="<?= format_number($item->quantity) ?>" id="quantity" name="quantity">
            <label class="mdl-textfield__label" for="quantity">Kwantitas</label>
            <?php if (!empty($errors['quantity'])): ?>
              <span class="form-error"><?= $errors['quantity'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?= !empty($errors['cost']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input numberEditor" type="text" value="<?= format_number($item->cost) ?>" id="cost" name="cost">
            <label class="mdl-textfield__label" for="cost">Harga</label>
            <?php if (!empty($errors['cost'])): ?>
              <span class="form-error"><?= $errors['cost'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
            <input class="mdl-textfield__input" type="text" value="<?= format_number($item->subtotalCost) ?>" id="subtotal" readonly>
            <label class="mdl-textfield__label" for="subtotal">Subtotal</label>
          </div>
        </div>
      </main>
    </form>
    <?= render('foot') ?>
    <script>
      var products = <?= json_encode($products) ?>;
      var productsByIds = new Map();
      var productsByNames = new Map();
      
      var i;
      for (i = 0; i < products.length; i++) {
        var p = products[i];
        productsByIds.set(p.id, p);
        productsByNames.set(p.name.toLowerCase(), p);
      }

      var productNameTextBox = document.querySelector('#productName');
      var quantityTextBox = document.querySelector('#quantity');
      var costTextBox = document.querySelector('#cost');
      var subtotalTextBox = document.querySelector('#subtotal');
      var productIdInput = document.querySelector('#productId');

      function updateSubtotal() {
        var quantity = parseInt(quantityTextBox.value.replace(".", ""));
        var cost = parseInt(costTextBox.value.replace(".", ""));
        subtotalTextBox.value = (quantity * cost).toLocale();
      }
      
      productNameTextBox.addEventListener('change', function() {
        productIdInput.value = "0";
         
        var selectedProductName = productNameTextBox.value.trim().toLowerCase();
        var selectedProduct = productsByNames.get(selectedProductName);
        if (selectedProduct) {
          productIdInput.value = selectedProduct.id;
          var cost = parseInt(costTextBox.value);
          if (isNaN(cost) || cost === 0) {
            costTextBox.value = parseInt(selectedProduct.cost).toLocale();
          }
        }         
      });
      
      quantityTextBox.addEventListener('change', updateSubtotal);
      costTextBox.addEventListener('change', updateSubtotal);
      
      updateSubtotal();

      var deleteButton = document.querySelector('#delete-button');
      if (deleteButton) {
        deleteButton.addEventListener('click', function(e) {
          if (!confirm('Hapus Produk?')) {
            e.preventDefault();
            return;
          }
        });
      }
    </script>
  </body>
</html>