<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./editor?id=<?= $item->parentId ?>" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= format_purchasing_order_code($item->parentId) ?></span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="save-button"
            type="submit" name="action" value="save"><i class="material-icons left">check</i></button>
          <?php if ($item->id): ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="delete-button" type="submit" name="action" value="delete">
              <i class="material-icons left">delete</i>
            </button>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <?php if ($item->id): ?>
            <input type="hidden" name="id" value="<?= $item->id ?>">
          <?php endif ?>
          <input type="hidden" name="parentId" value="<?= $item->parentId ?>">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--12-col">
            <select id="productId" name="productId" class="mdl-selectfield__select">
              <?php foreach ($products as $product): ?>
              <option value="<?= $product->id ?>" <?= $item->productId == $product->id ? 'selected' : '' ?>><?= $product->name ?></option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="productId">Produk</label>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col">
            <input class="mdl-textfield__input" type="text" value="<?= format_number($item->quantity) ?>" min="0" max="1000" id="quantity" name="quantity"
                   pattern="[0-9]+([\.][0-9]+)?" step="any">
            <label class="mdl-textfield__label" for="quantity">Kwantitas</label>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col">
            <input class="mdl-textfield__input" type="text" value="<?= format_number($item->cost) ?>" min="0" id="cost" name="cost">
            <label class="mdl-textfield__label" for="cost">Harga</label>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
            <input class="mdl-textfield__input" type="number" value="<?= format_number($item->subtotalCost) ?>" min="0" id="subtotal" readonly>
            <label class="mdl-textfield__label" for="subtotal">Subtotal</label>
          </div>
        </div>
      </main>
    </form>
    <?= render('foot') ?>
    <script>
      var costByProductIds = <?= json_encode($costByProductIds) ?>;

      Number.prototype.toLocale = function(c, d, t){
      var n = this, 
          c = isNaN(c = Math.abs(c)) ? 0 : c, 
          d = d == undefined ? "," : d, 
          t = t == undefined ? "." : t, 
          s = n < 0 ? "-" : "", 
          i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))), 
          j = (j = i.length) > 3 ? j % 3 : 0;
         return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
       };

      var productSelect = document.querySelector('#productId');
      var quantityTextBox = document.querySelector('#quantity');
      var costTextBox = document.querySelector('#cost');
      var subtotalTextBox = document.querySelector('#subtotal');

      function updateSubtotal() {
        subtotalTextBox.value =  (quantityTextBox.value.replace(".", "") * costTextBox.value.replace(".", "")).toLocale();
      }

      function updatePrice() {
        costTextBox.value = parseInt(costByProductIds[productSelect.value]).toLocale();
      }

      productSelect.addEventListener('change', updatePrice);
      quantityTextBox.addEventListener('change', updateSubtotal);
      costTextBox.addEventListener('change', updateSubtotal);
      quantityTextBox.addEventListener('focus', function () { this.select(); } );
      costTextBox.addEventListener('focus', function () { this.select(); } );

      updatePrice();
      updateSubtotal();

      var deleteButton = document.querySelector('#delete-button');
      if (deleteButton) {
        deleteButton.addEventListener('click', function(e) {
          if (!confirm('Hapus Kategori Produk?')) {
            e.preventDefault();
            return;
          }
        });
      }
    </script>
  </body>
</html>