<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
    #stock-adjustment-list .detail { line-height: 14px; font-size: 12px; }
    #stock-adjustment-list .title { font-weight: bold; }
  </style>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Pembelian</span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="filter-button" type="button">
            <i class="material-icons">filter_list</i>
          </button>
          <a href="./create" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">add</i>
          </a>
        </div>
      </header>
      <?= render('pos/drawer') ?>
      <main class="mdl-layout__content">
        <div id="stock-adjustment-list" class="mdlx-data-list">
          <?php foreach ($items as $item): ?>
            <div class="mdlx-data-list__item">
              <a href="./editor?id=<?= $item->id ?>">
                <div class="title">#<?= format_purchasing_order_code($item->id) ?> <?= date('d/m/Y H:i:s', strtotime($item->lastModDateTime)) ?></div>
                <div class="detail">
                  <?= format_purchasing_order_status($item->status) ?> | <?= format_number($item->totalCost) ?>
                </div>
              </a>
            </div>
          <?php endforeach ?>
        </div>
      </main>
    </div>
    <form method="GET">
      <dialog id="filter-dialog" class="mdl-dialog">
        <h4 class="mdl-dialog__title">Penyaringan</h4>
        <div class="mdl-dialog__content">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="status" name="status" class="mdl-selectfield__select">
                <option value="-1" <?= $filter['status'] === -1 ? 'selected' : '' ?>>Semua</option>
                <option value="0" <?= $filter['status'] === 0 ? 'selected' : '' ?>>Disimpan</option>
                <option value="1" <?= $filter['status'] === 1 ? 'selected' : '' ?>>Selesai</option>
                <option value="2" <?= $filter['status'] === 2 ? 'selected' : '' ?>>Dibatalkan</option>
            </select>
            <label class="mdl-selectfield__label" for="status">Status</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="lastmod" name="lastmod" class="mdl-selectfield__select">
              <option value="anytime" <?= $filter['lastmod'] === 'anytime' ? 'selected' : '' ?>>Kapan pun</option>
              <option value="thisweek" <?= $filter['lastmod'] === 'thisweek' ? 'selected' : '' ?>>Minggu Ini</option>
              <option value="prevweek" <?= $filter['lastmod'] === 'prevweek' ? 'selected' : '' ?>>Minggu Kemarin</option>
              <option value="thismonth" <?= $filter['lastmod'] === 'thismonth' ? 'selected' : '' ?>>Bulan Ini</option>
              <option value="prevmonth" <?= $filter['lastmod'] === 'prevmonth' ? 'selected' : '' ?>>Bulan Kemarin</option>
              <option value="thisyear" <?= $filter['lastmod'] === 'thisyear' ? 'selected' : '' ?>>Tahun Ini</option>
            </select>
            <label class="mdl-selectfield__label" for="lastmod">Perubahan Terakhir</label>
          </div>
        </div>
        <div class="mdl-dialog__actions">
          <button type="submit" class="mdl-button apply">OK</button>
          <button type="button" class="mdl-button close">batal</button>
        </div>
      </dialog>
    </form>
    <?= render('foot') ?>
    <script>      
      var filterDialog = document.querySelector('#filter-dialog');
      if (! filterDialog.showModal) {
        dialogPolyfill.registerDialog(filterDialog);
      }
      
      document.querySelector('#filter-dialog .close').addEventListener('click', function() {
        filterDialog.close();
      });
      
      document.querySelector('#filter-button').addEventListener('click', function() {
        filterDialog.showModal();
      });
    </script>
  </body>
</html>
