<form method="GET" class="mdl-grid">
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--2-col">
    <select id="status" name="status" class="mdl-selectfield__select">
      <option value="-1" <?= $status == -1 ? 'selected' : '' ?>>Semua</option>
      <option value="0" <?= $status == 0 ? 'selected' : '' ?>>Aktif</option>
      <option value="1" <?= $status == 1 ? 'selected' : '' ?>>Selesai</option>
      <option value="2" <?= $status == 2 ? 'selected' : '' ?>>Dibatalkan</option>
    </select>
    <label class="mdl-selectfield__label" for="status">Status</label>
  </div>
  <div class="mdl-cell mdl-cell--4-col buttons">
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit">
      <i class="material-icons left">check</i>Terapkan</button>
  </div>
  <?php if (empty($items)): ?>
    <p class="mdl-cell mdl-cell--12-col">Tidak ada item berdasarkan kriteria penyaringan yang Anda dipilih.</p>
  <?php else: ?>
    <div class="mdlx-data-table--responsive mdl-cell mdl-cell--12-col">
      <table class="mdl-data-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Waktu</th>
            <th>Status</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
        <?php foreach ($items as $item): ?>
          <tr>
            <td><a href="./editor?id=<?= $item->id ?>"><?= format_sales_order_code($item->id) ?></a></td>
            <td><?= date('d/m/Y H:i:s', strtotime($item->lastModDateTime)) ?></td>
            <td><?= format_stock_adjustment_status($item->status) ?></td>
            <td><?= format_number($item->totalCost) ?></td>
          </tr>
        <?php endforeach ?>
        </tbody>
      </table>
    </div>
  <?php endif ?>
</form>