<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
    #items {border-collapse: collapse;}
    #items td,#items th{border:1px solid black;padding: 2px 12px;}
    #items td:nth-child(2),#items td:nth-child(4), #items td:nth-child(5) { text-align: right;}
    #items td:nth-child(2) {border-right-style: none;padding-right:3px;}
    #items td:nth-child(3) {border-left-style: none;padding-left:3px;}
    *{color:#000;}
  </style>
  </head>
  <body>
    <div style="margin:0 auto;width:18cm;">
      <h5>Order Shift Komputer</h5>
      <p>
        #<?= format_purchasing_order_code($order->id) ?>
        | <?= format_purchasing_order_status($order->status) ?>: <?= to_locale_datetime($order->lastModDateTime) ?>
      </p>
      <table id="items">
        <thead>
          <tr>
            <th>Item</th>
            <th colspan="2">Qty</th>
            <?php if (!isset($_GET['dontShowCost'])): ?>
            <th>Cost</th>
            <th>SubTotal</th>
            <?php endif ?>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($order->items as $item): ?>
          <tr>
            <td><?= $item->productName ?></td>
            <td><?= format_number($item->quantity) ?></td>
            <td><?= e($item->productUom) ?></td>
            <?php if (!isset($_GET['dontShowCost'])): ?>
            <td><?= format_number($item->cost) ?></td>
            <td><?= format_number($item->subtotalCost) ?></td>
            <?php endif ?>
          </tr>
          <?php endforeach ?>
        </tbody>
        <?php if (!isset($_GET['dontShowCost'])): ?>
        <tfoot>
          <tr>
            <th colspan="4">Grand Total</th>
            <th style="text-align: right;"><?= format_number($order->totalCost) ?></th>
          </tr>
        </tfoot>
        <?php endif ?>        
      </table>
    </div>
  </body>
</html>
