<div class="mdl-layout__drawer">
  <header class="mdl-color--blue-grey mdl-color-text--white">
    <span class="mdl-layout-title">
      <a class="mdl-color-text--white" href="<?= BASE_URL ?>/debts/">Utang Piutang</a>
    </span>
    <span class="my-account-name"><a class="mdl-color-text--white" href="<?= BASE_URL ?>/account"><?= $_SESSION['CURRENT_USER']->username ?></a></span>
  </header>
  <nav class="mdl-navigation">
    <?php if (current_user_can('view-debts-accounts')): ?>
      <a class="mdl-navigation__link<?= str_starts_with($_SERVER['PATH_INFO'], '/debts/account/') ? ' active' : '' ?>"
        href="<?= BASE_URL ?>/debts/account/"><i class="material-icons">monetization_on</i>Utang Piutang</a>
      <hr>
    <?php endif ?>
    <a class="mdl-navigation__link" href="<?= BASE_URL ?>/"><i class="material-icons">arrow_back</i>Shift Apps</a>
  </nav>
</div>