<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
    .r {text-align:right}
    .h td{font-weight:bold;}
    table{margin:0;width:100%;}
    tr:first-child td:nth-child(2) {width:40px;}
    tr td:nth-child(2) {text-align: right;}
    tr:first-child td:nth-child(3) {width:90px;}
    tr:not(.h) td:first-child {padding-left:10px;}
  </style>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Utang Piutang</span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </header>
      <?= render('debts/drawer') ?>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-cell mdl-cell--4-col">
            <table>
              <tr class="h">
                <td colspan="4">Piutang</td>
              </tr>
              <tr>
                <td>Perorangan</td>
                <td>Rp.</td>
                <td class="r"><?= format_number($debts['personal'][0]) ?></td>
                <td class="r"><?= format_number($debts['personal'][1], 2) ?>%</td>
              </tr>
              <tr>
                <td>Perusahaan</td>
                <td>Rp.</td>
                <td class="r"><?= format_number($debts['company'][0]) ?></td>
                <td class="r"><?= format_number($debts['company'][1], 2) ?>%</td>
              </tr>
              <tr class="h">
                <td>Total Piutang</td>
                <td>Rp.</td>
                <td class="r"><?= format_number($debts['total']) ?></td>
                <td class="r"></td>
              </tr>
              <tr class="h">
                <td colspan="4">Utang</td>
              </tr>
              <tr>
                <td>Perorangan</td>
                <td>Rp.</td>
                <td class="r"><?= format_number($credits['personal'][0]) ?></td>
                <td class="r"><?= format_number($credits['personal'][1], 2) ?>%</td>
              </tr>
              <tr>
                <td>Perusahaan</td>
                <td>Rp.</td>
                <td class="r"><?= format_number($credits['company'][0]) ?></td>
                <td class="r"><?= format_number($credits['company'][1], 2) ?>%</td>
              </tr>
              <tr class="h">
                <td>Total Utang</td>
                <td>Rp.</td>
                <td class="r"><?= format_number($credits['total']) ?></td>
                <td></td>
              </tr>

              <tr class="h">
                <td>Balance</td>
                <td>Rp.</td>
                <td class="r"><?= format_number($balance) ?></td>
                <td></td>
              </tr>
            </table>
          </div>
        </div>
      </main>
    </div>
    <?= render('foot') ?>
  </body>
</html>
