<form method="POST" class="mdl-grid">
  <?php if ($item->id): ?>
    <input type="hidden" name="id" value="<?= $item->id ?>">
  <?php endif ?>
  <input type="hidden" name="parentId" value="<?= $item->parentId ?>">
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--12-col">
    <select id="productId" name="productId" class="mdl-selectfield__select">
      <option value="0" disabled>Pilih Produk:</option>
      <?php foreach ($products as $product): ?>
      <option value="<?= $product->id ?>" <?= $item->productId == $product->id ? 'selected' : '' ?>><?= $product->name ?></option>
      <?php endforeach ?>
    </select>
    <label class="mdl-selectfield__label" for="productId">Produk</label>
  </div>
  <div class="mdl-cell mdl-cell--12-col">
    <table id="price-info"><tbody></tbody></table>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col">
    <input class="mdl-textfield__input" type="text" value="<?= format_number($item->quantity) ?>" min="0" max="1000" id="quantity" name="quantity"
           pattern="[0-9]+([\.][0-9]+)?" step="any">
    <label class="mdl-textfield__label" for="quantity">Kwantitas</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col">
    <input class="mdl-textfield__input" type="text" value="<?= format_number($item->price) ?>" min="0" id="price" name="price">
    <label class="mdl-textfield__label" for="price">Harga</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
    <input class="mdl-textfield__input" type="number" value="<?= format_number($item->subtotalPrice) ?>" min="0" id="subtotal" readonly>
    <label class="mdl-textfield__label" for="subtotal">Subtotal</label>
  </div>
  <div class="mdl-cell mdl-cell--12-col buttons">
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit" name="action" value="save">
      <i class="material-icons left">check</i>Simpan</button>
    <?php if ($item->id): ?>
    <button class="mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect" type="submit" name="action" value="delete">
    <i class="material-icons left">delete</i>Hapus</button>
    <?php endif ?>
  </div>
</form>
<script>
  var priceByProductIds = <?= json_encode($priceByProductIds) ?>;
  Number.prototype.toLocale = function(c, d, t){
  var n = this, 
      c = isNaN(c = Math.abs(c)) ? 0 : c, 
      d = d == undefined ? "," : d, 
      t = t == undefined ? "." : t, 
      s = n < 0 ? "-" : "", 
      i = String(parseInt(n = Math.abs(Number(n) || 0).toFixed(c))), 
      j = (j = i.length) > 3 ? j % 3 : 0;
     return s + (j ? i.substr(0, j) + t : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : "");
   };
 
  var productSelect = document.querySelector('#productId');
  var quantityTextBox = document.querySelector('#quantity');
  var priceTextBox = document.querySelector('#price');
  var subtotalTextBox = document.querySelector('#subtotal');
  var priceInfoTable = document.querySelector('#price-info');
  
  function updateSubtotal() {
    subtotalTextBox.value =  (quantityTextBox.value.replace(".", "") * priceTextBox.value.replace(".", "")).toLocale();
  }
  
  function formatPrice(item, i) {
    var min = parseInt(item['price' + i + 'Min']);
    var max = parseInt(item['price' + i + 'Max']);
    if (min !== 0 || max !== 0) {
      if (min !== max) {
        return max.toLocale() + ' - ' + min.toLocale();
      }
      else {
        return max.toLocale();
      }
    }
    return "";
  }
  
  function updatePriceInfo() {
    priceInfoTable.children[0].innerHTML = "";
    var id = productSelect.value;
    if (!id) return;
    var prices = priceByProductIds[id];
    if (!prices)
      return;
    
    var html = "";
    
    if (prices.length > 0) {
      html += '<tr><td colspan="3">Info harga:</td></tr>';
      
      for (var i = 0; i < prices.length; i++) {
        var item = prices[i];
        
        html += '<tr>';
        if (item.quantityMax == 0) {
          html += '<td> >= ' + parseInt(item.quantityMin).toLocale() + '</td>';
        }
        else {
          html += '<td>' + parseInt(item.quantityMin).toLocale() + ' - ' + parseInt(item.quantityMax).toLocale() + '</td>';
        }
        var strArray = [];

        for (var j = 1; j <= 3; j++) {
          var priceStr = formatPrice(item, j);
          if (priceStr.length > 0)
            strArray.push(priceStr);
        }
        
        html += '<td>:</td>'
        html += '<td>' +  strArray.join(" / ") + '</td>';
        html += '</tr>';
      }
    }
    priceInfoTable.children[0].innerHTML = html;
  }

  productSelect.addEventListener('change', updatePriceInfo);
  quantityTextBox.addEventListener('change', updateSubtotal);
  priceTextBox.addEventListener('change', updateSubtotal);
  
  updatePriceInfo();
  updateSubtotal();
</script>