<!DOCTYPE html>
<html lang="id">
  <head>
    <?= render('head') ?>
    <style>
      .g {color:green;}.r{color:red;}
    </style>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= e($account->name) ?></span>
          <div class="mdl-layout-spacer"></div>
          <?php if (current_user_can('add-finance-transaction')): ?>
          <a class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect"
            href="./transaction-editor?accountId=<?= $account->id ?>"><i class="material-icons left">add</i></a>
          <?php endif ?>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="filter-button" type="button">
            <i class="material-icons">filter_list</i>
          </button>
          <?php if (current_user_can('edit-finance-account') || current_user_can('transfer-cash')): ?>
            <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="more-button" type="button">
              <i class="material-icons">more_vert</i>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="more-button">
              <?php if (current_user_can('transfer-cash')): ?>
              <li class="mdl-menu__item">
                <a href="./transfer?fromId=<?= $account->id ?>"><i class="material-icons left">compare_arrows</i> Transfer</a>
              </li>
              <?php endif ?>
              <?php if (current_user_can('edit-finance-account')): ?>
                <li class="mdl-menu__item">
                  <a href="./editor?id=<?= $account->id ?>"><i class="material-icons left">edit</i> Edit</a>
                </li>
              <?php endif ?>
            </ul>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdlx-data-list">
          <div class="mdlx-data-list__item" style="background:#eee;">
            <div style="float:right;text-align:right;">
              <span><b><?= format_number($account->lastBalance) ?></b></span>
            </div>
            <div><b>SALDO AKHIR</b></div>
          </div>
          <?php $balance = $account->lastBalance ?>
          <?php foreach ($items as $item): ?>
          <?php
            $balanceAfter = $balance;
            $balanceBefore = $balance - $item->amount;
          ?>
            <div class="mdlx-data-list__item">
              <div style="float:right;text-align:right;">
                <span class="<?= $item->amount > 0 ? 'g' : 'r' ?>"><b><?=
                  ($item->amount > 0 ? '+' : '') . format_number($item->amount) ?></b></span><br>
                  <small><?= format_number($balanceAfter) ?></small>
              </div>
              <div>
                <a href="./transaction-editor?id=<?= $item->id ?>">
                <?= e($item->description) ?>
                </a>
              </div>
              <small><?= to_locale_datetime($item->dateTime) ?></small>
            </div>
          <?php $balance -= $item->amount ?>
          <?php endforeach ?>
          <div class="mdlx-data-list__item" style="background:#eee;">
            <div style="float:right;text-align:right;">
              <span><b><?= format_number($balance) ?></b></span>
            </div>
            <div><b>SALDO AWAL</b></div>
          </div>
        </div>
      </main>
    </form>
    <form method="GET">
      <input type="hidden" name="id" value="<?= $account->id ?>">
      <dialog id="filter-dialog" class="mdl-dialog">
        <h4 class="mdl-dialog__title">Penyaringan</h4>
        <div class="mdl-dialog__content">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="date" name="date" class="mdl-selectfield__select">
              <option value="today" <?= $filter['date'] === 'today' ? 'selected' : '' ?>>Hari Ini</option>
              <option value="yesterday" <?= $filter['date'] === 'yesterday' ? 'selected' : '' ?>>Kemarin</option>
              <option value="thisweek" <?= $filter['date'] === 'thisweek' ? 'selected' : '' ?>>Minggu Ini</option>
              <option value="prevweek" <?= $filter['date'] === 'prevweek' ? 'selected' : '' ?>>Minggu Kemarin</option>
              <option value="thismonth" <?= $filter['date'] === 'thismonth' ? 'selected' : '' ?>>Bulan Ini</option>
              <option value="prevmonth" <?= $filter['date'] === 'prevmonth' ? 'selected' : '' ?>>Bulan Kemarin</option>
            </select>
            <label class="mdl-selectfield__label" for="date">Tanggal</label>
          </div>
        </div>
        <div class="mdl-dialog__actions">
          <button type="submit" class="mdl-button apply">OK</button>
          <button type="button" class="mdl-button close">batal</button>
        </div>
      </dialog>
    </form>
    <?= render('foot') ?>
    <script>
      confirmOnClick('#delete-button', 'Hapus akun?');
      setupStandardFilterDialog();
    </script>
  </body>
</html>