<form method="GET" class="mdl-grid">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
    <input class="mdl-textfield__input" type="text" value="<?= $datetime->format('d/m/Y') ?>" id="date" name="date">
    <label class="mdl-textfield__label" for="date">Tanggal Shift</label>
  </div>
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--4-col">
    <select id="clientId" name="clientId" class="mdl-selectfield__select">
      <option value="0">Semua Client</option>
      <?php foreach ($clients as $client): ?>
        <option value="<?= $client->id ?>" <?= $client->id == $clientId ? 'selected' : '' ?>>Client <?= $client->id ?></option>
      <?php endforeach ?>
    </select>
    <label class="mdl-selectfield__label" for="clientId">Client</label>
  </div>
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--4-col">
    <select id="groupId" name="groupId" class="mdl-selectfield__select">
      <option value="0">Semua Grup</option>
      <?php foreach ($groups as $id => $name): ?>
        <option value="<?= $id ?>" <?= $id == $groupId ? 'selected' : '' ?>><?= $name ?></option>
      <?php endforeach ?>
    </select>
    <label class="mdl-selectfield__label" for="groupId">Grup</label>
  </div>
  <div class="mdl-cell mdl-cell--6-col buttons">
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit">
      <i class="material-icons left">check</i>Terapkan</button>
  </div>
  <?php if (empty($activities)): ?>
  <p class="mdl-cell mdl-cell--12-col">Tidak ada aktifitas berdasarkan kriteria yang dipilih.</p>
  <?php else: ?>
  <style>
    .mdl-data-table th .material-icons { vertical-align: middle; }
    .mdl-data-table tr>*{text-align:left;}
    .mdl-data-table tr>*:nth-child(1),
    .mdl-data-table tr>*:nth-child(2)
    {text-align:center;}
    .mdl-data-table tr>*:nth-child(1){width:110px;}
    .mdl-data-table tr>*:nth-child(2){width:60px;}
    
  </style>
  <div class="mdlx-data-table--responsive mdl-cell mdl-cell--12-col">
    <table class="mdl-data-table">
      <thead>
        <tr>
          <th><i class="material-icons">access_time</i></th>
          <th><i class="material-icons">desktop_windows</i></th>
          <th><i class="material-icons">supervisor_account</i></th>
          <th>Rincian</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($activities as $activity): ?>
        <tr>
          <td><?= date('H:i:s', strtotime($activity->dateTime)) ?></td>
          <td><?= $activity->clientId ?></td>
          <td><?= $activity->username ?></td>
          <td><?= $activity->detail ?></td>
        </tr>
      <?php endforeach ?>
      </tbody>
    </table>
  </div>
  <?php endif ?>
</form>