<form method="POST" class="mdl-grid">
  <h5 class="mdl-cell mdl-cell--12-col">Info Umum</h5>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--8-col <?=
    !empty($errors['name']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="text" value="<?= e($product->name) ?>" maxlength="100" id="name" name="name">
    <label class="mdl-textfield__label" for="name">Nama Produk</label>
    <?php if (!empty($errors['name'])): ?>
      <span class="form-error"><?= $errors['name'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--2-col">
    <select id="type" name="type" class="mdl-selectfield__select">
      <option value="<?= ProductTypes::NonStocked ?>" <?= $product->type == ProductTypes::NonStocked ? 'selected' : '' ?>>Non Stok</option>
      <option value="<?= ProductTypes::Stocked ?>" <?= $product->type == ProductTypes::Stocked ? 'selected' : '' ?>>Stok</option>
      <option value="<?= ProductTypes::Service ?>" <?= $product->type == ProductTypes::Service ? 'selected' : '' ?>>Jasa</option>
    </select>
    <label class="mdl-selectfield__label" for="type">Jenis</label>
  </div>
  <div class="mdl-cell mdl-cell--2-col">
    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="active">
      <input type="checkbox" id="active" class="mdl-checkbox__input" value="1" name="active" <?= $product->active ? 'checked' : '' ?>>
      <span class="mdl-checkbox__label">Aktif</span>
    </label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col <?= !empty($errors['uom']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="text" value="<?= e($product->baseUom->name) ?>" maxlength="20" id="uom" name="uom">
    <label class="mdl-textfield__label" for="uom">Satuan Dasar</label>
    <?php if (!empty($errors['uom'])): ?>
      <span class="form-error"><?= $errors['uom'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--4-col">
    <select id="costingMethod" name="costingMethod" class="mdl-selectfield__select">
      <option value="<?= ProductCostingMethods::Manual ?>" <?=
        $product->costingMethod == ProductCostingMethods::Manual ? 'selected' : '' ?>>Manual</option>
      <option value="<?= ProductCostingMethods::Average ?>" <?=
        $product->costingMethod == ProductCostingMethods::Average ? 'selected' : '' ?>>Rata-rata harga beli</option>
      <option value="<?= ProductCostingMethods::LastPurchase ?>" <?=
        $product->costingMethod == ProductCostingMethods::LastPurchase ? 'selected' : '' ?>>Harga beli terakhir</option>
    </select>
    <label class="mdl-selectfield__label" for="costingMethod">Metode Penentuan Modal</label>
  </div>
  
  <div class="mdl-cell mdl-cell--12-col buttons">
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit">
      <i class="material-icons left">check</i>Simpan</button>
    <a href="./" class="mdl-button mdl-button--raised  mdl-js-button mdl-js-ripple-effect">
      <i class="material-icons left">close</i>Batal</a>
  </div>
</form>