<style>
  .mdl-data-table .mdl-textfield {margin:0;padding:0;width:100px;}
</style>
<form method="POST" class="mdl-grid">
  <?php if ($product->id): ?>
    <input type="hidden" name="id" value="<?= $product->id ?>">
  <?php endif ?>
  <div class="mdl-cell mdl-cell--12-col buttons">
    <button class="mdl-button mdl-button--raised mdl-button--accent mdl-js-button mdl-js-ripple-effect" type="submit" name="action" value="save">
      <i class="material-icons left">check</i>Simpan</button>
    <button class="mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect" type="submit" name="action" value="delete">
      <i class="material-icons left">delete</i>Hapus</button>
  </div>
  <h5 class="mdl-cell mdl-cell--12-col">Info Umum</h5>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--8-col <?=
    !empty($errors['name']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="text" value="<?= e($product->name) ?>" maxlength="100" id="name" name="name">
    <label class="mdl-textfield__label" for="name">Nama Produk</label>
    <?php if (!empty($errors['name'])): ?>
      <span class="form-error"><?= $errors['name'] ?></span>
    <?php endif ?>
  </div>
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--2-col">
    <select id="type" name="type" class="mdl-selectfield__select">
      <?php foreach (Product::getTypes() as $k => $v): ?>
      <option value="<?= $k ?>" <?= $product->type == $k ? 'selected' : '' ?>><?= $v ?></option>
      <?php endforeach ?>
    </select>
    <label class="mdl-selectfield__label" for="type">Jenis</label>
  </div>
  <div class="mdl-cell mdl-cell--2-col">
    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="active">
      <input type="checkbox" id="active" class="mdl-checkbox__input" value="1" name="active" <?= $product->active ? 'checked' : '' ?>>
      <span class="mdl-checkbox__label">Aktif</span>
    </label>
  </div>
  <h5 class="mdl-cell mdl-cell--12-col">Satuan</h5>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?= !empty($errors['uom']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="text" value="<?= e($product->uom) ?>" maxlength="20" id="uom" name="uom">
    <label class="mdl-textfield__label" for="uom">Satuan Dasar</label>
    <?php if (!empty($errors['uom'])): ?>
      <span class="form-error"><?= $errors['uom'] ?></span>
    <?php endif ?>
  </div>
  <h5 class="mdl-cell mdl-cell--12-col">Modal</h5>
  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label mdl-cell mdl-cell--4-col">
    <select id="costingMethod" name="costingMethod" class="mdl-selectfield__select">
      <?php foreach (Product::getCostingMethods() as $k => $v): ?>
      <option value="<?= $k ?>" <?= $product->costingMethod == $k ? 'selected' : '' ?>><?= $v ?></option>
      <?php endforeach ?>
    </select>
    <label class="mdl-selectfield__label" for="costingMethod">Metode Penentuan Modal</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
    !empty($errors['manualCost']) ? 'is-invalid' : '' ?>">
    <input class="mdl-textfield__input" type="text" value="<?= format_number($product->manualCost) ?>"
           maxlength="10" id="manualCost" name="manualCost">
    <label class="mdl-textfield__label" for="manualCost">Modal</label>
    <?php if (!empty($errors['manualCost'])): ?>
      <span class="form-error"><?= $errors['manualCost'] ?></span>
    <?php endif ?>
  </div>
</form>