<div class="mdl-grid table-container">
  <?php if (count($products) == 0 ): ?>
    <p class="mdl-cell mdl-cell--12-col">Tidak ada produk.</p>
  <?php else: ?>
    <div class="mdl-cell mdl-cell--12-col mdlx-data-table--responsive">
      <table id="product-list-table" class="mdl-data-table">
        <thead>
          <tr>
            <th>Kode</th>
            <th>Nama</th>
            <th>Stok</th>
            <th>Jenis</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($products as $product): ?>
          <tr>
            <td><a href="./editor?id=<?= $product->id ?>"><?= format_product_code($product->id) ?></a></td>
            <td><?= e($product->name) ?></td>
            <td><?= e($product->getStockInfo()) ?></td>
            <td><?= $product->getTypeName() ?></td>
            <td><?= $product->active ? 'Aktif' : 'Nonaktif' ?></td>
          </tr>
          <?php endforeach ?>
          <tr style="display:none;" id="empty-result-info">
            <td colspan="3" style="text-align:center;font-style:italic;">Tidak ditemukan</td>
          </tr>
        </tbody>
      </table>
    </div>
  <?php endif ?>  
</div>