<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  <style>
    #product-list .info { line-height: 14px; font-size: 12px; }
    #product-list .name { font-weight: bold; }
  </style>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Produk (<?= format_number(count($products)) . '/'. format_number($productCount) ?>)</span>
          <div class="mdl-layout-spacer"></div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search-product-textbox"><i class="material-icons">search</i></label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" id="search-product-textbox" onkeyup="applyFilter()">
            </div>
          </div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="filter-button" type="button">
            <i class="material-icons">filter_list</i>
          </button>
          <?php if (current_user_can('add-product')): ?>
          <a href="./editor" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">add</i>
          </a>
          <?php endif ?>
        </div>
      </header>
      <?= render('pos/drawer') ?>
      <main class="mdl-layout__content">
        <div id="product-list" class="mdlx-data-list">
          <?php foreach ($products as $product): ?>
            <div class="mdlx-data-list__item <?= $product->active ? '' : 'r' ?>">
              <a href="./editor?id=<?= $product->id ?>">
                <div class="name"><?= e($product->name) ?></div>
                <div class="info"><?= format_product_code($product->id) ?></div>
                <div class="info">
                  <?php if ($product->type != Product::ShiftNetVoucher): ?>
                  <div>
                    <?php if ($product->type == Product::Stocked): ?>
                      <span>Stok: <?= $product->getStockInfo() ?></span>
                      <?php if (current_user_can('view-product-cost')): ?>
                      | <span><?= $product->getCostingMethodName() ?>: <?= format_number($product->cost) ?></span>
                      <?php endif ?>
                    <?php endif ?>
                  </div>
                  <?php endif ?>
                  <?php if ($info = $product->getPriceInfo()): ?>
                    <div><?= $info ?></div>
                  <?php endif ?>
                </div>
              </a>
            </div>
          <?php endforeach ?>
        </div>
      </main>
    </div>
    <form method="GET">
      <dialog id="filter-dialog" class="mdl-dialog">
        <h4 class="mdl-dialog__title">Penyaringan</h4>
        <div class="mdl-dialog__content">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="categoryId" class="mdl-selectfield__select" name="categoryId">
              <option value="-1" <?= $filter['categoryId'] === -1 ? 'selected' : '' ?>>Semua Kategori</option>
              <option value="0" <?= $filter['categoryId'] === 0 ? 'selected' : '' ?>>Tanpa Kategori</option>
              <?php foreach ($categories as $category): ?>
                <option value="<?= $category->id ?>" <?= $filter['categoryId'] === (int)$category->id ? 'selected' : '' ?>><?= e($category->name) ?></option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="categoryId">Kategori</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="type" name="type" class="mdl-selectfield__select">
              <option value="-1" <?= $filter['type'] === -1 ? 'selected' : '' ?>>Semua</option>
              <?php foreach (Product::getTypes() as $k => $v): ?>
                <option value="<?= $k ?>" <?= $filter['type'] === $k ? 'selected' : '' ?>><?= $v ?></option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="type">Jenis</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="status" name="status" class="mdl-selectfield__select">
                <option value="-1" <?= $filter['status'] === -1 ? 'selected' : '' ?>>Semua</option>
                <option value="1" <?= $filter['status'] === 1 ? 'selected' : '' ?>>Aktif</option>
                <option value="0" <?= $filter['status'] === 0 ? 'selected' : '' ?>>Tidak Aktif</option>
            </select>
            <label class="mdl-selectfield__label" for="status">Status</label>
          </div>
        </div>
        <div class="mdl-dialog__actions">
          <button type="submit" class="mdl-button apply">OK</button>
          <button type="button" class="mdl-button close">batal</button>
        </div>
      </dialog>
    </form>
    <?= render('foot') ?>
    <script>
      function applyFilter() {
        
        var input, filter, rows, productNameElement, productCodeElement, i;
        input = document.getElementById("search-product-textbox");
        filter = input.value.toUpperCase();
        rows = document.querySelectorAll("#product-list>div");
        for (i = 0; i < rows.length; i++) {
          productNameElement = rows[i].children[0].children[0];
          productCodeElement = rows[i].children[0].children[1];
          if (productNameElement) {
            if (productNameElement.innerHTML.toUpperCase().indexOf(filter) > -1
                || productCodeElement.innerHTML.toUpperCase().indexOf(filter) > -1) {
              rows[i].style.display = "";
            } else {
              rows[i].style.display = "none";
            }
          }
        }
      }
      
      setupStandardFilterDialog();
    </script>
  </body>
</html>
