<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdlx-layout__no-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <a href="./editor?id=<?= $product->id ?>" class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">arrow_back</i>
          </a>
          <span class="mdl-layout-title"><?= !$uom->id ? 'Tambah' : 'Edit' ?> Satuan</span>
          <div class="mdl-layout-spacer"></div>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect"
            type="submit" name="action" value="save" id="save-button"><i class="material-icons left">save</i></button>
          <?php if ($uom->id): ?>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="more-button" type="button">
            <i class="material-icons">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="more-button">
            <li class="mdl-menu__item">
              <button type="submit" name="action" value="delete" id="delete-button"><i class="material-icons left">delete</i> Hapus</button>
            </li>
          </ul>
          <?php endif ?>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <input type="hidden" name="id" value="<?= $uom->id ?>">
          <input type="hidden" name="productId" value="<?= $uom->productId ?>">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
            <input class="mdl-textfield__input" type="text" readonly id="productName" value="<?= e($product->name) ?>">
            <label class="mdl-textfield__label" for="productName">Nama Produk</label>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?=
            !empty($errors['name']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="text" value="<?= e($uom->name) ?>" maxlength="100" id="name" name="name">
            <label class="mdl-textfield__label" for="name">Nama Satuan</label>
            <?php if (!empty($errors['name'])): ?>
              <span class="form-error"><?= $errors['name'] ?></span>
            <?php endif ?>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--2-col <?= !empty($errors['quantity']) ? 'is-invalid' : '' ?>">
            <input class="mdl-textfield__input" type="number" min="0" step="1" value="<?= $uom->quantity ?>" maxlength="20" id="quantity" name="quantity">
            <label class="mdl-textfield__label" for="quantity">Kwantitas</label>
            <?php if (!empty($errors['quantity'])): ?>
              <span class="form-error"><?= $errors['quantity'] ?></span>
            <?php endif ?>
          </div>
        </div>
        <div class="mdl-grid">
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--4-col">
            <input class="mdl-textfield__input" type="text" readonly id="description">
            <label class="mdl-textfield__label" for="description">Contoh Konversi</label>
          </div>
        </div>
      </main>
    </form>
    <?= render('foot') ?>
    <script>
      var nameTextBox = document.querySelector('#name'),
          quantityTextBox = document.querySelector('#quantity'),
          descriptionTextBox = document.querySelector('#description');

      function updateDescription() {
        descriptionTextBox.value = '1 ' + nameTextBox.value + ' = ' + quantityTextBox.value + ' <?= e($product->uom) ?>';
      }

      nameTextBox.addEventListener('change', updateDescription);
      quantityTextBox.addEventListener('change', updateDescription);
      updateDescription();
      
      document.querySelector('#save-button').addEventListener('click', showSubmitProgress);
      <?php if ($uom->id): ?>
      document.querySelector('#delete-button').addEventListener('click', function(e) {
        if (!confirm('Hapus Satuan?')) {
          e.preventDefault();
          return;
        }
        showSubmitProgress();
      });
      <?php endif ?>
    </script>
  </body>
</html>