<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body id="dashboard">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Operasional</span>
          <div class="mdl-layout-spacer"></div>
        </div>
      </header>
      <?= render('operational-cost/drawer') ?>
      <main class="mdl-layout__content">
        <div class="mdl-grid">
        </div>
      </main>
    </div>
    <?= render('foot') ?>
  </body>
</html>
