<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error 404 - Shift IMS</title>
    <style>
      body { font-family: "Calibri", "Helvetica",sans-serif; font-size: 14px; font-weight: 400; line-height: 20px; }
    </style>
  </head>
  <body>
    <h1>Error 404</h1>
    <p>Halaman <b><?= e($_SERVER['PATH_INFO']) ?></b> tidak ditemukan.</p>
  </body>
</html>